### PR TITLE
Refactor basic material on category theory

### PR DESCRIPTION
**Pull request by siddharthist**
This change introduces a new subdirectory `CategoryTheory/Core` that holds foundational material on category theory. The motivation is that the files `Categories.v` and `functor_categories.v` were becoming quite long, and the material in them was split quite naturally among a few different topics.

In brief:
 - Categories, functors, and natural transformations now each have a dedicated file with their definitions and ubiquitous, elementary lemmas about them
 - Material on functor categories has been moved to its own file
 - A file `Core/Prelude.v` exports a set of material that I anticipate that most nontrivial developments on category theory will need, for convenience of imports. I elected to individually import the material in `Core` in pre-existing files (in part to see what materially is most frequently used), but anticipate that many newly-added files will choose to import `Core.Prelude` instead.

### CODE REVIEW

**Comment by siddharthist** [comment]
I developed a very rudimentary tool to help me fix many of the import errors that arose in such a large refactoring. It's available here: https://github.com/siddharthist/coq-imports

**Comment by DanGrayson** [comment]
lgtm

**Comment by benediktahrens** [comment]
```
COQC UniMath/CategoryTheory/Monads/RelMonads_Coreflection.v
File "./UniMath/CategoryTheory/Monads/RelMonads_Coreflection.v", line 21, characters 15-48:
Error: Unable to locate library UniMath.CategoryTheory.Categories.
```
due to merging PR #1059

**Comment by benediktahrens** [comment]
Also a merge conflict here.

**Comment by siddharthist** [comment]
Fixed

**Pull request merged**
