### PR TITLE
make with 2 jobs on github action

### PR DESCRIPTION
**Pull request by benediktahrens**
The runners have 2 cores, so we could speed this up a bit: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

However, Coq sometimes does not like being compiled with more than 1 job, so I am leaving it as is.

### CODE REVIEW

**Comment by benediktahrens** [comment]
There is still a Travis residue in this PR's status message. The Github Action succeeds, the Travis action seems to be hanging. 

I have suspended Travis' access to the repositories in the UniMath organization - how about uninstalling it completely?

**Comment by DanGrayson** [comment]
> There is still a Travis residue in this PR's status message. The Github Action succeeds, the Travis action seems to be hanging.
> 
> I have suspended Travis' access to the repositories in the UniMath organization - how about uninstalling it completely?

I tried that, but it warned that it would affect all 16 repositories, so it seems to be a bad idea.

**Comment by DanGrayson** [comment]
> > There is still a Travis residue in this PR's status message. The Github Action succeeds, the Travis action seems to be hanging.
> > I have suspended Travis' access to the repositories in the UniMath organization - how about uninstalling it completely?
> 
> I tried that, but it warned that it would affect all 16 repositories, so it seems to be a bad idea.

We should check whether the suspension affects all 16 repositories.

**Comment by benediktahrens** [comment]
> We should check whether the suspension affects all 16 repositories.

It does affect all 16 repositories, but from what I see, only UniMath/Schools still relies on it - and I am planning to switch that one over to github actions.

Travis has been horribly unreliable anyway.

**Comment by benediktahrens** [comment]
Obsolete, closing.

**Pull request closed without merging**
