### PR TITLE
improve citation suggestion for UniMath

### PR DESCRIPTION
**Pull request by benediktahrens**
- give a more descriptive title
- improve the colon that Vladimir once complained about ("what does it mean?"); the emdash, by convention, indicates a subtitle
- remove manual formatting "\em", which should not be part of a bibtex entry

### CODE REVIEW

**Comment by peterlefanulumsdaine** [comment]
Two cents: I very much like the more descriptive title, and the removal of manual formatting.

I think of colons as being just as standard as em-dashes to indicate a subtitle; that point seems fine to me either way.

**Comment by DanGrayson** [comment]
I suggest this slight change:

```
@Misc{UniMath,
    author = {Voevodsky, Vladimir and Ahrens, Benedikt and Grayson, Daniel and others},
    title = {{UniMath --- a computer-checked library of univalent mathematics}},
    url = {https://github.com/UniMath/UniMath},
    howpublished = {{available} at \url{https://github.com/UniMath/UniMath}}
 }
```

Line wrapping works better if we don't tell TeX that "UniMath---a" is a single word.

The amsplain bibliography style doesn't display the url, so it is good to put the link also in another item.  Anyone who ends up with bibliography that displays the link twice can delete one of the two items, but someone who ends up with no hyperlink will probably just ignore it.

**Comment by DanGrayson** [comment]
PS: TeXlive has 335 bibliography style files that recognize "howpublished" and 158 that recognize "url".

**Comment by benediktahrens** [comment]
On 28/01/18 12:43, Daniel R. Grayson wrote:
> I suggest this slight change:
> 
> |@Misc{UniMath, author = {Voevodsky, Vladimir and Ahrens, Benedikt and 
> Grayson, Daniel and others}, title = {{UniMath --- a computer-checked 
> library of univalent mathematics}}, url = 
> {https://github.com/UniMath/UniMath}, howpublished = {{available} at 
> \url{https://github.com/UniMath/UniMath}} } |
> 
> Line wrapping works better if we don't tell TeX that "UniMath---a" is a 
> single word.
> 
> The amsplain bibliography style doesn't display the url, so it is good 
> to put the link also in another item. Anyone who ends up with 
> bibliography that displays the link twice can delete one of the two 
> items, but someone who ends up with no hyperlink will probably just 
> ignore it.

Thanks a lot - improvements incorporated through latest commit to the PR 
branch.

**Pull request merged**
