### PR TITLE
split out stuff on adjunctions into separate file

### PR DESCRIPTION
**Pull request by benediktahrens**
This PR addresses the first point mentioned in #588 : make a separate file on adjunctions.

### CODE REVIEW

**Comment by mortberg** [comment]
How about merging AdjunctionsHomTypesWeq into Adjunctions? That's a basic result about adjunctions and it makes sense to me to have it in the same file to make it easier to find.

**Comment by mortberg** [comment]
Apart from my comment above: LGTM

**Comment by benediktahrens** [comment]
On 02/22/2017 02:40 PM, Anders Mörtberg wrote:
> How about merging AdjunctionsHomTypesWeq into Adjunctions? That's a
> basic result about adjunctions and it makes sense to me to have it in
> the same file to make it easier to find.

Ok, in a separate PR.

**Comment by DanGrayson** [comment]
lgtm

**Pull request merged**
