### PR TITLE
Adapt to https://github.com/coq/coq/pull/18705

### PR DESCRIPTION
**Pull request by proux01**
Adapt to https://github.com/coq/coq/pull/18705
This is backward compatible (down to Coq 8.16).

### CODE REVIEW

**Review by nmvdw — APPROVED** [review]

**Comment by rmatthes** [comment]
@benediktahrens: Coq 8.18 is no longer being used by CI, "Coq latest" is now Coq 8.19.0.

**Comment by rmatthes** [comment]
Is it clear what fails here? Of course, the sanity check fails if the proposal includes the Foundations package.

**Comment by proux01** [comment]
Anyway, the PR is currently a noop so it cannot be a coqc failure.

**Comment by proux01** [comment]
Maybe this can be merged so as to not delay the upstream PR on Coq? This is a noop and #1848 is completely orthogonal anyway.

**Comment by benediktahrens** [comment]
> Maybe this can be merged so as to not delay the upstream PR on Coq? This is a noop and #1848 is completely orthogonal anyway.

@proux01 : this PR is failing all of our CI, without any error message. Without understanding better, it seems we cannot merge this PR.

**Comment by nmvdw** [comment]
> > Maybe this can be merged so as to not delay the upstream PR on Coq? This is a noop and #1848 is completely orthogonal anyway.
> 
> @proux01 : this PR is failing all of our CI, without any error message. Without understanding better, it seems we cannot merge this PR.

I tried to compile this PR locally (using https://github.com/proux01/UniMath/pull/1), and I noticed this PR **does** seem to break compilation.

More specifically, if I run this PR, then the following line hangs:
```coq
Definition TRRGraph_univalence_weq2 (G H : TRRGraph) : G ╝ H ≃ G ≅ H.
Proof.
  use weqbandf.
```
(in `UniMath/Combinatorics/ZFstructures.v`).

However, if I perform this line on the current master version of UniMath, it goes immediately.

I think this is the reason why the sanity checks fail.

**Comment by rmatthes** [comment]
I see that the force-pushed changes put much fewer reversible directives. Are the others needed? What is the criterion?

**Comment by proux01** [comment]
Sorry, I realized that the bug I'm trying to fix in https://github.com/coq/coq/pull/18705 doesn't affect
```Coq
Coercion foo : bar >-> baz.  (* non reversible coercion, as documented *)
```
but only
```
Coercion foo := bar.  (* reversible by default, contrary to what the doc reads (only record fields with `:>` should be reversible by default) *)
```

Anyway, the CI is mostly green but there is still a failure with Coq dev, is it the already known one?

**Comment by proux01** [comment]
FWIW, I locally confirmed that this overlay works with the upstream PR and what gets tested in Coq's CI, so as far as I'm concerned this is in a mergeable state.

I guess once the upstream PR is merged and you'll require Coq >= 8.20, you may want to remove some, maybe most, of the `#[reversible]` (or add more, I still don't know whether you want reversible coercions or not).

**Comment by nmvdw** [comment]
> FWIW, I locally confirmed that this overlay works with the upstream PR and what gets tested in Coq's CI, so as far as I'm concerned this is in a mergeable state.

The reason why the CI fails, has to do with the fact that the Bicategories/SubstitutionSystems are not checked in the Coq CI, while recently an error was introduced (https://github.com/coq/coq/issues/18593). The UniMath CI does take these packages into account.

> I guess once the upstream PR is merged and you'll require Coq >= 8.20, you may want to remove some, maybe most, of the `#[reversible]` (or add more, I still don't know whether you want reversible coercions or not).

I think that most coercions in UniMath should not be reversible. However, interestingly enough, it turns out that we use that some coercions are reversible (i.e., `dcpo_struct_to_PartialOrder`), which we were not aware of.

Is there a way to only set the coercions that must be reversible to be reversible? So: only a minimal set of coercions are set to be reversible?

**Comment by proux01** [comment]
> The reason why the CI fails, has to do with the fact that the Bicategories/SubstitutionSystems are not checked in the Coq CI, while recently an error was introduced ([coq/coq#18593](https://github.com/coq/coq/issues/18593)). The UniMath CI does take these packages into account.

Thanks for confirming this is the already known issue (and thus perfectly orthogonal to the current PR).
 
> I think that most coercions in UniMath should not be reversible.

Ok

> However, interestingly enough, it turns out that we use that some coercions are reversible (i.e., `dcpo_struct_to_PartialOrder`), which we were not aware of.

Yes, that's what makes the current PR required in the first place (otherwise I could have just fixed the Coq bug without you having to even care about it).

> Is there a way to only set the coercions that must be reversible to be reversible? So: only a minimal set of coercions are set to be reversible?

I guess that's what you want to do, but I'm not gonna do it for you, I already lost way too much time with the current PR (sure, I'm the one responsible for the bug in the first place but still).

**Comment by proux01** [comment]
Thanks

**Comment by benediktahrens** [comment]
@proux01 : thanks a lot for preparing this PR!

**Pull request merged**
