### PR TITLE
Real numbers are a complete field

### PR DESCRIPTION
**Pull request by cathlelay**
I succeed to prove the completeness of real numbers.
There is still some work to have real numbers, but I should have less difficulties.

### CODE REVIEW

**Comment by DanGrayson** [comment]
You may want to also prove ` isdeceq boolDcuts `.

**Comment by DanGrayson** [comment]
The abbreviation provided by this definition provides not much shortening, so could be eliminated:
```
Definition ex_lim_seq (u : nat -> hr_ConstructiveField) := Σ l, is_lim_seq u l.
```

**Comment by DanGrayson** [comment]
Here would be a clearer statement of a lemma:
```
Lemma hr_to_NR (X : hr_commrng) :
  Σ x : NonnegativeReals × NonnegativeReals,
        pr1 X x × ( pr1 x = 0 ∨ pr2 x = 0 ).
```
Or also this:
```
Lemma hr_to_NR (X : hr_commrng) :
  ( Σ x : NonnegativeReals, X = NR_to_hr (x,,0) )
  ∨
  ( Σ x : NonnegativeReals, X = NR_to_hr (0,,x) ).
```

**Comment by DanGrayson** [comment]
Looks good to me!

**Comment by cathlelay** [comment]
Do you talk about "Lim" ?
I defined it to have statements which are easier to read.

2015-12-09 18:35 GMT-05:00 Daniel R. Grayson <notifications@github.com>:

**Comment by DanGrayson** [comment]
What does "There is still some work to have real numbers" mean?

**Comment by cathlelay** [comment]
To provide such definition, I need to be able to prove which is the smaller
element between (pr1 y) and (pr2 y) for all y in (pr1 X). It is impossible
because "less than" is not decidable.

2015-12-09 18:58 GMT-05:00 Daniel R. Grayson <notifications@github.com>:

**Comment by cathlelay** [comment]
I did not prove yet that order is compatible with addition and
multiplication.

And, I also plan to have, as for NonnegativeRationals and NonnegativeReals,
an "interface" to ease the use of real numbers.

2015-12-09 19:06 GMT-05:00 Daniel R. Grayson <notifications@github.com>:

**Comment by DanGrayson** [comment]
Looks good to me.

**Comment by cathlelay** [comment]
Addition and multiplication are compatible with orders ("less than" and "less or equal").

**Comment by DanGrayson** [comment]
Re: "To provide such definition, I need to be able to prove which is the smaller
element between (pr1 y) and (pr2 y) for all y in (pr1 X). It is impossible
because "less than" is not decidable."

Thanks.  Now I appreciate the ingeniousness of your lemma `hr_to_NR`!

**Comment by DanGrayson** [comment]
So now there is nothing more to prove about the real numbers?

**Comment by DanGrayson** [comment]
This pull request of Catherine's is okay with me.  Is anyone else planning to comment?

**Comment by vladimirias** [comment]
Ok with me.

**Comment by benediktahrens** [comment]
On 12/16/2015 05:29 PM, Daniel R. Grayson wrote:
> This pull request of Catherine's is okay with me.  Is anyone else
> planning to comment?

I am not.

**Pull request merged**
