### PR TITLE
Summary: improve INSTALL (bash under MAC OS)

### PR DESCRIPTION
**Pull request by DanGrayson**
Now that the Makefile uses a feature of recent versions of bash, Mac OS X users
may have to install a recent version of bash, so here we modify the install
instructions.  The feature is associative arrays, declared with `declare -A`.

Here is homebrew's bash:
```
$ /usr/local/bin/bash --version
GNU bash, version 4.4.5(1)-release (x86_64-apple-darwin16.3.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```
Here is the Mac OS X bash:
```
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```

### CODE REVIEW

**Comment by mortberg** [comment]
I'm not a MAC user, but this looks good to me

**Comment by peterlefanulumsdaine** [comment]
I am a Mac user, and can confirm that this is good.

In more detail: the “enforce-linear-order” check broke the build on my system, with the message
```
bash: line 0: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
make: *** [enforce-linear-ordering] Error 2
```
and installing a newer bash with `brew install bash` fixed it.

(Including the gory details so that other users with the same problem can hopefully find this thread.)

**Comment by benediktahrens** [comment]
How about the makefile skips the check if a too old bash is detected?
If I were a Mac user, I'd be pretty upset about having to get a new bash just to compile UniMath with 
```
$ make
```

**Comment by peterlefanulumsdaine** [comment]
Actually, I second Benedikt’s suggestion as even better.  It was a bit frustrating having my build broken by this, given that it’s not actually needed for compiling the library.  :-)

**Comment by DanGrayson** [comment]
Okay, will do.  Travis has a recent bash, so at least Travis will check this, and developers should be told to install a recent bash, so their pull requests will pass the test.

**Comment by DanGrayson** [comment]
From Peter's link: "Apple will not update Bash, because the latest version is licensed under GPLv3, which Apple cannot use. "

So that explains it, sigh!  Maybe I'll go back to gnu-linux for my next laptop.

**Comment by DanGrayson** [comment]
Okay, that should do it.  Good thing I looked at it -- I found some other errors.  It wasn't doing the enforcement early enough, and it could be waylaid by a too-old version of "sed".

**Pull request merged**
