### PR TITLE
Avoid relying on `Export` bugs

### PR DESCRIPTION
**Pull request by maximedenes**
See https://github.com/coq/coq/issues/10474 and
https://github.com/coq/coq/issues/10480

This is in preparation for https://github.com/coq/coq/pull/10476 which fixes these two bugs, and is backward compatible (tested on Coq's master).

### CODE REVIEW

**Comment by benediktahrens** [comment]
@maximedenes : Thanks a lot for preparing this PR!

Could you briefly explain, e.g., why the fix in  UniMath/CategoryTheory/ExactCategories/ExactCategories.v is necessary, moving the 
```
Require ExportUniMath.MoreFoundations.Propositions.
```
to a later place? Does it have to do with some constant in that file (module) being shadowed by another one of the same name in another module?

**Comment by DanGrayson** [comment]
Thanks, looks good to me.

**Comment by maximedenes** [comment]
> Does it have to do with some constant in that file (module) being shadowed by another one of the same name in another module?

It is because there is an unfortunate clash of notations: `∃! x, P` is defined as `iscontr [...]` in `Fondations.PartA` and `iscontr_hProp [...]` in `MoreFoundations.Propositions`.

**Comment by benediktahrens** [comment]
@maximedenes : Thanks for your explanation, and thanks again for your help in maintaining UniMath!

@DanGrayson : I have opened https://github.com/UniMath/UniMath/issues/1253 regarding the clash of notation.

**Pull request merged**
