### PR TITLE
remove trailing white space from all lines

### LINKED ISSUE #131: Several files: terminal white space
There are several files which contain instances of terminal white space, i.e., white space after periods, etc.  Perhaps these can be removed.

### PR DESCRIPTION
**Pull request by DanGrayson**
resolves #131

### CODE REVIEW

**Comment by benediktahrens** [comment]
A general remark: this is a rather big patch for not much benefit. 
For the sake of keeping the repository small, I would like to avoid this kind of patch.
Also, it is very difficult to check this patch, because of missing line wrapping in the Github code view.

That being said, I don't want to oppose integration of this patch.

**Comment by vladimirias** [comment]
I would very much prefer not to add anything that is hard to understand to the repository.

White spaces at the end of the lines is not something that a common user would be concerned with is it?

**Comment by vladimirias** [comment]
Sorry, I take my comment back, just too tired (it’s 10:58pm in Singapore).

**Comment by DanGrayson** [comment]
The benefit from removing white space is nil, as far as I can see.
Checking the patch is easy, though, using the "-b" option to "git diff" --
you'll be informed that, modulo changes to white space, there are no
changes.  Repository size is no problem, though, since git stores slight
changes efficiently, and since computers are gigantic.

**Comment by benediktahrens** [comment]
LGTM

**Comment by DanGrayson** [comment]
Let's not bother with removing white space.  Closing.

**Pull request closed without merging**
