### PR TITLE
Reorganize results about the precategory of types

### PR DESCRIPTION
**Pull request by siddharthist**
This structure mirrors that introduced for HSET in #1060

Also introduces a partial classification of monics and the result that `idtoiso` is an equivalence.

### CODE REVIEW

**Comment by siddharthist** [comment]
Hmm Travis seems to think I changed Foundations?

**Comment by DanGrayson** [comment]
Hmm, no, I take that back ...

**Comment by DanGrayson** [comment]
Here's the error message:
```
error: *** file UniMath/CategoryTheory/categories/Types.v not listed in appropriate file UniMath/*/.package/files
error: *** file UniMath/CategoryTheory/categories/Type/Structures.v not listed in appropriate file UniMath/*/.package/files
error: *** 2 unlisted proof files encountered
Makefile:384: recipe for target 'enforce-listing-of-proof-files' failed
```

**Comment by siddharthist** [comment]
This is fixed.

**Comment by siddharthist** [comment]
This has been updated.

**Comment by siddharthist** [comment]
This has conflicts due to the merge of #1142, I'll fix it soon.

**Comment by siddharthist** [comment]
This is ready for merge

**Pull request merged**
