### PR TITLE
Five lemma and HomologicalAlgebra package

### PR DESCRIPTION
**Pull request by tpannila**
This pull request contains formalization of the 5-lemma and a new package, HomologicalAlgebra, see
#520 . Here is a summary of the changes
- Some new stuff on short exact sequences. Most of these are used to prove the 5-lemma. Some 
  of these will be used later to develop derived functors.
- AbelianPushoutPullback.v contains results on pushouts of monics and pullbacks of epis. These are
  used to prove the 5-lemma.
- PseudoElements.v contains formalization of pseudo elements. These are used to prove the  
  5-lemma. 
- FiveLemma.v contains formalization of the 5-lemma. As a corollary of 5-lemma, there is a version
  of it for short exact sequences.

I moved the following files from CategoryTheory to HomologicalAlgebra
- Complexes.v
- CohomologyComplex.v

### CODE REVIEW

**Comment by benediktahrens** [comment]
Tomi, could you please also add your new package to the file .travis.yml?

**Comment by DanGrayson** [comment]
It's good that this will no longer be part of CategoryTheory, since it isn't category theory.

**Comment by DanGrayson** [comment]
`UniMath/README.md` should document that the name of each new package should also be added to `.travis.yml`.

**Comment by benediktahrens** [comment]
@tpannila could you please merge master into your branch, so that the Travis configuration file will be updated in this branch?

**Pull request merged**
