### PR TITLE
Remove use of `Unset Automatic Introduction`

### PR DESCRIPTION
**Pull request by ejgallego**
Clean up use of deprecated option.

cc #1052

### CODE REVIEW

**Comment by ejgallego** [comment]
Ups, this is not ready yet, sorry; I will amend ASAP.

**Comment by ejgallego** [comment]
This should now be complete.

**Comment by benediktahrens** [comment]
@ejgallego : Thank you very much!

**Comment by ejgallego** [comment]
Thanks to you folks!

**Pull request merged**
