### PR TITLE
add unit category

### PR DESCRIPTION
**Pull request by benediktahrens**
- one-element category
- unique functor from any precategory

### CODE REVIEW

**Comment by DanGrayson** [comment]
Perhaps instead or also move 
```
Definition path_groupoid (X:UU) : isofhlevel 3 X -> category.
```
and
```
Definition cat_n (n:nat):category.
```
upstream from Ktheory?

**Comment by rmatthes** [comment]
So, this category is only "morally" terminal. Is there a policy of not mentioning "morality"?

**Comment by benediktahrens** [comment]
On 04/13/2017 01:59 PM, Ralph Matthes wrote:
> So, this category is only "morally" terminal. Is there a policy of
> not mentioning "morality"?

I would need to make this category an inhabitant of a (bi)category to
discuss terminality.
That's left for future work.

**Comment by benediktahrens** [comment]
On 04/13/2017 01:48 PM, Daniel R. Grayson wrote:
> Perhaps instead or also move 
> ```
> Definition path_groupoid (X:UU) : isofhlevel 3 X -> category.
> ```
> and
> ```
> Definition cat_n (n:nat):category.
> ```
> upstream from Ktheory?
> 

Sure, that would be very helpful.
How about merging the material in a future PR?

**Comment by DanGrayson** [comment]
Sure, leave it for the future.

**Comment by benediktahrens** [comment]
Is this one good to merge?

**Comment by DanGrayson** [comment]
lgtm

**Comment by benediktahrens** [comment]
I implement Dan's suggestion instead, closing this PR.

**Pull request closed without merging**
