### PR TITLE
add a memory limit of 2500000K

### PR DESCRIPTION
**Pull request by DanGrayson**
... for reproducibility of results when running under travis, and
to prevent wasting memory.

See also https://github.com/UniMath/UniMath/pull/1272#issuecomment-517942592

### CODE REVIEW

**Comment by benediktahrens** [comment]
https://travis-ci.org/UniMath/UniMath/jobs/568054692#L1631:

```
--- making UniMath/Paradoxes/All.v

--- making UniMath/Induction/All.v

--- making UniMath/All.v

ulimit -v 2000000 ; +make -f build/CoqMakefile.make UniMath/Foundations/Init.vo UniMath/Foundations/Preamble.vo UniMath/Foundations/PartA.vo UniMath/Foundations/PartB.vo UniMath/Foundations/UnivalenceAxiom.vo UniMath/Foundations/PartC.vo UniMath/Foundations/PartD.vo UniMath/Foundations/UnivalenceAxiom2.vo UniMath/Foundations/Propositions.vo UniMath/Foundations/Sets.vo UniMath/Foundations/NaturalNumbers.vo UniMath/Foundations/Tests.vo UniMath/Foundations/HLevels.vo UniMath/Foundations/All.vo

bash: +make: command not found

Makefile:147: recipe for target 'Foundations' failed

make: *** [Foundations] Error 127
```

**Comment by DanGrayson** [comment]
```
COQC UniMath/CategoryTheory/Bicategories/DisplayedBicats/Fibration/Fibration1.v
Fatal error: out of memory.
```

**Comment by benediktahrens** [comment]
Is there a way to make this memory limit optional, and to only activate it on Travis?

One often writes a first version of a proof that uses quite a lot of memory, and then iteratively improves that proof. I would find it important that one can still continue the development despite having a construction that uses more memory than some limit.

**Comment by siddharthist** [comment]
Travis sets the `CI` environment variable ([among others](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables)), so the `ulimit` could happen conditionally based on that.

**Comment by DanGrayson** [comment]
> Is there a way to make this memory limit optional, and to only activate it on Travis?
> 
> One often writes a first version of a proof that uses quite a lot of memory, and then iteratively improves that proof. I would find it important that one can still continue the development despite having a construction that uses more memory than some limit.

There are two ways:

-  Add `MEMORY_LIMIT=unlimited` to the `make` command line.
-  Follow the directions in `build/Makefile-configuration-template` and change the memory limit there.

**Comment by benediktahrens** [comment]
On 06/08/2019 13:22, Daniel R. Grayson wrote:
>     Is there a way to make this memory limit optional, and to only
>     activate it on Travis?
> 
>     One often writes a first version of a proof that uses quite a lot of
>     memory, and then iteratively improves that proof. I would find it
>     important that one can still continue the development despite having
>     a construction that uses more memory than some limit.
> 
> There are two ways:
> 
>   * Add |MEMORY_LIMIT=unlimited| to the |make| command line.
>   * Follow the directions in |build/Makefile-configuration-template| and
>     change the memory limit there.

Would it be better to have users opt *into* the memory limitation, 
rather than have them opt *out*?

**Comment by DanGrayson** [comment]
> Would it be better to have users opt *into* the memory limitation, rather than have them opt *out*?

I think not, for then they will be surprised when travis fails.

By the way, the limit is ineffective in Mac OS X, sadly.

**Comment by benediktahrens** [comment]
On 06/08/2019 19:58, Daniel R. Grayson wrote:
>     Would it be better to have users opt /into/ the memory limitation,
>     rather than have them opt /out/?
> 
> I think not, for then they will be surprised when travis fails.
> 
> By the way, the limit is ineffective in Mac OS X, sadly.

I think that the standard setup should work the same on Linux and Mac 
OS, in particular when using UniMath for teaching.

It would hence be better to have an opt-in for the memory limit.

**Pull request merged**
