### PR TITLE
For coq trunk unpatched

### PR DESCRIPTION
**Pull request by DanGrayson**
We take the work Benedikt did getting UniMath to compile with coq v8.5, unpatched
by us, but we keep the current makefile system working.  This will take care
of https://github.com/UniMath/UniMath/issues/92

### CODE REVIEW

**Comment by vladimirias** [comment]
What happened in UniMath/RezkCompletion/precomp_ess_surj.v l. 361 and below. Why suddenly two of the arguments of something called Y need not be typed in anymore?

**Comment by benediktahrens** [comment]
On 05/14/2015 12:51 PM, Vladimir Voevodsky wrote:
> What happened in UniMath/RezkCompletion/precomp_ess_surj.v l. 361 and
> below. Why suddenly two of the arguments of something called Y need
> not be typed in anymore?

The first two arguments of Y had been marked as implicit since the 
beginning, but Coq did not take that into account previously: despite 
having them marked as implicit, I still had to give those arguments 
later on.

The new Coq version behaves correctly, and so I could (and needed to) 
remove the two implicit arguments of Y.

(Those two arguments indicate source and target of the third argument, 
which is a morphism in some precategory.)

**Comment by benediktahrens** [comment]
LGTM

**Comment by DanGrayson** [comment]
Travis is very picky about white space.

Okay to merge, now that travis approves?

**Comment by vladimirias** [comment]
Ok with me.

**Pull request merged**
