### PR TITLE
reduce number of reversible coercions

### PR DESCRIPTION
**Pull request by rmatthes**
This partially undoes PR #1850.

Currently, it concerns 99 of the 259 reversibility declarations. I only found 5 worthy to retain. I'll try to look at the others as well.

Unfortunately, this PR sits on the already merged PR #1858. So, only my commits are relevant. The file comparison should be okay (not be cluttered because of that).

Update: 250 of the 259 reversibility declarations are now gone. In one single case was the need for reversibility circumvented by a small code modification. The other 9 reversible coercions are now in use. If CI goes well, this completes the present PR.

### CODE REVIEW

**Comment by nmvdw** [comment]
How did you do this? Did you consider the coercions by hand or did you automate it some way?

**Comment by rmatthes** [comment]
This was guesswork and trial and error. But not too bad. I did not yet make a full compilation locally, so I may have to pull back.

**Comment by nmvdw** [comment]
If I checked correctly, only the following reversible coercions remain:
```
UniMath/CategoryTheory/TwoSidedDisplayedCats/TwoSidedDispCat.v:  #[reversible] Coercion twosided_disp_cat_to_twosided_disp_cat_data
UniMath/CategoryTheory/DisplayedCats/Examples/Arrow.v:#[reversible] Coercion arrow_mor {C : category} (f : arrow C) := pr2 f.
UniMath/CategoryTheory/DisplayedCats/Examples/Arrow.v:#[reversible] Coercion mor_to_arrow_ob {C : category} {x y : C} (f : x --> y) : arrow C :=
UniMath/CategoryTheory/EnrichedCats/Colimits/EnrichedCoequalizers.v:  #[reversible] Coercion ob_enriched_coequalizer_cocone
UniMath/CategoryTheory/EnrichedCats/Colimits/EnrichedCoproducts.v:  #[reversible] Coercion ob_enriched_coprod_cocone
UniMath/CategoryTheory/EnrichedCats/Limits/EnrichedEqualizers.v:  #[reversible] Coercion ob_enriched_equalizer_cone
UniMath/CategoryTheory/EnrichedCats/Limits/EnrichedProducts.v:  #[reversible] Coercion ob_enriched_prod_cone
UniMath/OrderTheory/DCPOs/Core/Basics.v:#[reversible] Coercion dcpo_struct_to_PartialOrder
UniMath/OrderTheory/DCPOs/Core/Basics.v:#[reversible] Coercion dcppo_struct_to_dcpo_struct
```
I checked, and it seems like at some point, reversible coercions indeed are used. For example, in the following fragment `ob_enriched_prod_cone` is used as a reversible coercion.
```coq
  Let prod_src : C := pr1 (PE I D).
  Let is_prod_src : is_prod_enriched E D prod_src := pr2 (PE I D).
```
Here `PE I D` has type `: ∑ a : enriched_prod_cone E D, is_prod_enriched E D a`, and for `prod_src`, I only take the first projection and coerce it to something of type `C` (forgetting that it is a product cone). To type `is_prod_src`, it thus needs to be reconstructed that it is a cone, and for that the coercion is reversed.

The reversible coercions could be avoided by using the following instead.
```coq
  Let prod_src : enriched_prod_cone E D := pr1 (PE I D).
  Let is_prod_src : is_prod_enriched E D prod_src := pr2 (PE I D).

  Let prod_tar : enriched_prod_cone E _
    := pr1 (PE (∑ (x : I) (y : I), x --> y) (λ z, D (pr12 z))).
  Let is_prod_tar : is_prod_enriched E _ prod_tar
    := pr2 (PE (∑ (x : I) (y : I), x --> y) (λ z, D (pr12 z))).
```
For this PR, I think these coercions do not have to be made reversible.

I think this example explains why one might to use reversible coercions.

**Review by nmvdw — APPROVED** [review]

**Comment by rmatthes** [comment]
Indeed, the nine reversible coercions are used with their reversibility, but those uses might be avoided. Like I avoided the reversible coercion from univalent categories to categories in the only non-trivial modification of the present PR in file DisplayedArrowUniversalOnCat.v (marked in https://github.com/UniMath/UniMath/pull/1859/files#diff-a7b7ee5b851ef712d30bd5aac2a0502cdec1a61b0da303739347e57ad6d968ac).

**Review by benediktahrens — APPROVED** [review]

**Pull request merged**
