### PR TITLE
improve computability of weqbandf

### PR DESCRIPTION
**Pull request by DanGrayson**
resolves https://github.com/UniMath/UniMath/issues/278

### CODE REVIEW

**Comment by benediktahrens** [comment]
Now that's a nice example of what I have been trying to explain, that we should avoid destruct on pairs.

**Comment by benediktahrens** [comment]
lgtm

**Comment by mortberg** [comment]
Or that Coq really should have eta for pairs...

**Comment by DanGrayson** [comment]
Which it will when we switch to using primitive projections.

**Comment by mortberg** [comment]
Yes! :+1:

**Pull request merged**
