### PR TITLE
Limits and Colimits

### PR DESCRIPTION
**Pull request by DanGrayson**
This addresses the slowness issue #229.  It contains various facts about representable
functors, including
```
Theorem functorPrecategoryBinaryProduct (B C:Precategory) :
  hasBinaryProducts C -> hasBinaryProducts [B,C].
```
, which is proved from a general theorem about family of representable functors, bypassing
colimits (which can be dealt with in the same way):
```
Lemma bifunctor_assoc_repn {B C:Precategory} (X : [B, [C^op,SET]]) :
  (∀ b, Representation (X ◾ b)) -> Representation (bifunctor_assoc X).
```
No serious slowness is observed.

### CODE REVIEW

**Comment by mortberg** [comment]
Did you try to adapt SubstitutionSystems to use this definition? As far as I remember we had no problem with slowness before trying to use our formalization of colimits in functor categories there. 

Also why did you end has_homsets_opp with Defined instead of Qed?

**Comment by benediktahrens** [comment]
To test this, it seems best to have a file that introduces the same definitions and lemmas as in Coproducts.v .

Am 11. Dezember 2015 10:01:59 EST, schrieb "Anders Mörtberg" <notifications@github.com>:

**Comment by vladimirias** [comment]
LGTM.

Dan, do you have, for a functor eta:C->D and an object X of C the morphism Yo(X) -> eta\circ Yo(eta(X)) and a lemma saying that it is an equivalence (isomorphism) when eta is fully faithful? I think we may also need that it is natural in X (here Yo is the Yoneda to contravariant functors and \circ is in the diagrammatic order).

**Comment by DanGrayson** [comment]
Re : "Did you try to adapt SubstitutionSystems to use this definition? " 

No, I haven't looked at the code.

Re: "Also why did you end has_homsets_opp with Defined instead of Qed?"

I don't usually use Qed unless I have a reason to.

Re: "To test this, it seems best to have a file that introduces the same definitions and lemmas as in Coproducts.v ."

I'll take a look.

Re: "do you have, for a functor eta:C->D and an object X of C the morphism Yo(X) -> eta\circ Yo(eta(X)) and a lemma saying that it is an equivalence (isomorphism) when eta is fully faithful?"

I have this theorem, which ought to suffice and says that representability and embeddings:
```
Definition embeddingRepresentability {C D:Precategory}
           {i:C==>D} (emb:fully_faithful i) {Y:D^op==>SET} (s:Representation Y) :
           (Σ c, universalObject s = i c) -> Representation (Y □ functor_opp i).
```
One may use it, for example, to show that abelian groups have products by showing first that groups have products and then showing that the group product of a family of abelian groups is abelian.

**Pull request closed without merging**
