### PR TITLE
compile less of Coq

### PR DESCRIPTION
**Pull request by benediktahrens**
see #167

### CODE REVIEW

**Comment by DanGrayson** [comment]
That saves a lot of time (at home).  I bet travis will finish.

**Comment by DanGrayson** [comment]
Looks good, merging!  (40 minute build time, this probably made the difference.)

**Comment by benediktahrens** [comment]
The more abstract interface to making the Prelude seems to be the target "states". Should I correct this?

**Comment by DanGrayson** [comment]
Yes, that would be good.

**Pull request merged**
