### PR TITLE
More examples of comprehension bicategories

### PR DESCRIPTION
**Pull request by nmvdw**
- Added the notion of display map bicategory
- Each display map bicategory gives rise to a displayed bicategory with a global cleaving
- In some cases, we also get a local (op)cleaving)
- Instances of this notion: internal Street (op)fibrations

### CODE REVIEW

**Comment by nmvdw** [comment]
Error:
```
COQC UniMath/Foundations/Init.v
1149
COQC UniMath/Foundations/Preamble.v
1150
File "./UniMath/Foundations/Preamble.v", line 12, characters 15-39:
1151
Error: Unable to locate library UniMath.Foundations.Init.
1152
```

**Comment by benediktahrens** [comment]
> Error:
> 
> ```
> COQC UniMath/Foundations/Init.v
> 1149
> COQC UniMath/Foundations/Preamble.v
> 1150
> File "./UniMath/Foundations/Preamble.v", line 12, characters 15-39:
> 1151
> Error: Unable to locate library UniMath.Foundations.Init.
> 1152
> ```

I am restarting the CI jobs - maybe something weird on the build system.
@DanGrayson : have you seen something like this before?

**Comment by benediktahrens** [comment]
Compilation worked on my machine, merging.

**Comment by benediktahrens** [comment]
> > Error:
> > ```
> > COQC UniMath/Foundations/Init.v
> > 1149
> > COQC UniMath/Foundations/Preamble.v
> > 1150
> > File "./UniMath/Foundations/Preamble.v", line 12, characters 15-39:
> > 1151
> > Error: Unable to locate library UniMath.Foundations.Init.
> > 1152
> > ```
> 
> I am restarting the CI jobs - maybe something weird on the build system. @DanGrayson : have you seen something like this before?

I suspect that the CI error was caused by a missing file, see #1440, even though the error mesage is entirely unrelated.

**Comment by DanGrayson** [comment]
> > Error:
> > ```
> > COQC UniMath/Foundations/Init.v
> > 1149
> > COQC UniMath/Foundations/Preamble.v
> > 1150
> > File "./UniMath/Foundations/Preamble.v", line 12, characters 15-39:
> > 1151
> > Error: Unable to locate library UniMath.Foundations.Init.
> > 1152
> > ```
> 
> I am restarting the CI jobs - maybe something weird on the build system. @DanGrayson : have you seen something like this before?

Nope.  Sometimes things fail for weird reasons, though.

**Pull request merged**
