### PR TITLE
builder when displayed cat is locally propositional

### PR DESCRIPTION
**Pull request by rmatthes**
first example: monoidal full subcategory
this does not avoid code but is conceptually clearer

also builders for displayed binary products and displayed terminal objects in the locally propositional case

### CODE REVIEW

**Comment by rmatthes** [comment]
I think that the new builder in `Projections` should already appear in `Core` since it will be useful in `Constructions`. Many more simplifications of examples seem possible.

**Review by nmvdw — APPROVED** [review]
Nice.

**Comment by nmvdw** [comment]
> I think that the new builder in `Projections` should already appear in `Core` since it will be useful in `Constructions`. Many more simplifications of examples seem possible.

My opinion on this matter is stronger: the whole directory on displayed categories needs cleaning and refactoring. The current structure makes it hard to find stuff and difficult to find where stuff should be put. I would thus suggest to keep this refactoring maybe outside of this PR.

**Comment by benediktahrens** [comment]
```
--- checking the ordering prescribed by the files UniMath/*/.packages/files ---
error: *** UniMath/CategoryTheory/coslicecat.vo should not require UniMath/CategoryTheory/DisplayedCats/Projection.vo
1 dependency order errors in package listings
```

**Comment by rmatthes** [comment]
Okay, no refactoring. But I moved locally propositional to `Core.v`. This also solves the problem Benedikt spotted on compilation ordering. I'll do the other examples of monoidal categories.

**Review by nmvdw — APPROVED** [review]

**Pull request merged**
