### PR TITLE
precategory of abelian groups is a category

### PR DESCRIPTION
**Pull request by tpannila**
This PR contains 
- Univalence for setwith2binops, `setwith2binop_univalence`
- Univalence for monoids, `monoid_univalence`
- Univlaence for groups, `gr_univalence`
- Univalence for abelian groups, `abgr_univalence`
- The precategory of abelian groups is a category, `abgr_precategory_is_category`.

I created a file Equivalences.v in MoreFoundations which contains two weak equivalences.
- `weq_total2_fiber_dirprod_total2` is used in proving univalence for monoids and
  abelian groups.
- `weqtotal2assoc` is used in proving univalence for groups.

### CODE REVIEW

**Comment by DanGrayson** [comment]
lgtm.  @benediktahrens ?

**Comment by vladimirias** [comment]
I am traveling, but I want to repeat the same question - did the proof give a chance to use Catherine’s lemmas about the transfer of various binary product properties along equivalences?

**Comment by benediktahrens** [comment]
lgtm

**Comment by tpannila** [comment]
> I want to repeat the same question - did the proof give a chance to use Catherine’s 
> lemmas about the transfer of various binary product properties along equivalences?

@vladimirias No, as far as I know. The proofs in this PR are built on top of Dan's technique for 
setwithbinop. I have already formalized univalence for rigs, commrigs, rngs, commrngs, 
intdoms, and flds on my computer, and all these proofs are also built on Dan's method.

**Comment by AnthonyBordg** [comment]
Hi,

@vladimirias : can you give a specific reference for Catherine's lemmas you are talking about ?

**Comment by tpannila** [comment]
@AnthonyBordg , Search for `fwd` and `bck` in BinaryOperations.v . 

@DanGrayson , can you merge this PR? I wish to do a separate PR for rigs, commrigs, 
rngs, commrngs, intdoms, and flds to keep my pull requests small so that they are easier 
to review.

**Comment by AnthonyBordg** [comment]
@tpannila thanks. 
I don't clearly see how these lemmas on the transport of binary operations and their properties along an equivalence could be used to prove that a precategory is a category, for instance in the case of setwithbinop or abgr. 
Has Vladimir or anyone else any insight about this ? If yes, I would be glad, since this week I will try to prove that my precategory of R-modules is a category.

**Pull request merged**
