### PR TITLE
improve travis script

### PR DESCRIPTION
**Pull request by DanGrayson**
by specifying ocaml compiler version to opam

This is probably better than #859 at dealing with #858

### CODE REVIEW

**Comment by DanGrayson** [comment]
lgtm

It might even resolve #858

**Comment by benediktahrens** [comment]
Is there a reason why you think that specifying a particular version of ocaml will reduce the likelihood of failure? 

lgtm

**Comment by DanGrayson** [comment]
Maybe no precise reason, but it would be more predictable, and I did pay a little attention to the original error message that you reported:
```
[ERROR] No OCaml compiler found in path. You should use:
    opam init --comp=VERSION
```

**Comment by DanGrayson** [comment]
We had some reports of the library num not being available.  That's an example of an incompatibility caused by the use of different versions of ocaml, for starting with 4.06, num wasn't included.  And old versions of opam may deliver old versions of ocaml, by default.

**Comment by palmskog** [comment]
@DanGrayson These changes don't seem to have fixed the problem, as seen in this [build](https://travis-ci.org/UniMath/UniMath/jobs/322615798). One avenue worth trying out is to use explicit `apt-get` commands rather than the `apt` add-on in the Travis script. Unless you object, I will submit a pull request to try this out.

**Comment by DanGrayson** [comment]
Sure, let's go back to using apt-get, as we did before, if it will help.

By the way, it's good that specifying ocaml 4.06.0 caused the job to stop early.

**Pull request merged**
