### PR TITLE
remove file on left kan extension

### PR DESCRIPTION
**Pull request by benediktahrens**
see #1614

### CODE REVIEW

**Comment by nmvdw** [comment]
`CONTENTS.md` needs to be pushed

**Comment by benediktahrens** [comment]
@nmvdw : Thanks for fixing the error. Is a similar change possible for the file on left Kan extensions?

**Comment by nmvdw** [comment]
This PR fixes the Coq CI, and it deletes the file on Left Kan extensions. However, that's not a big problem, so for that reason, I merge it.

**Comment by nmvdw** [comment]
> @nmvdw : Thanks for fixing the error. Is a similar change possible for the file on left Kan extensions?

I dunno. I would need to look at that, but I will do that later (at some point in the future).

**Pull request merged**
