### PR TITLE
a few more constants opacified in colimit stuff

### PR DESCRIPTION
**Pull request by benediktahrens**

### CODE REVIEW

**Comment by DanGrayson** [comment]
Okay with me.

Do the changes help in some respect?

**Comment by benediktahrens** [comment]
On 02/22/2016 02:20 PM, Daniel R. Grayson wrote:
> Okay with me.
>
> Do the changes help in some respect?

No, not really, unfortunately. There are still two issues with our lists:

a) they don't compute. By that I mean that evaluating (functions into) 
lists make the computer explode.

b) the goal becomes quickly too big to understand what's going on, since 
too much stuff is unfolded.

I did the changes of this PR to experiment a bit, but could not solve 
the issues. However, the changes seem necessary (or beneficial) on the 
way to a solution anyway, so I thought I should push them.

I hope to specify the problems better soon.

**Comment by DanGrayson** [comment]
I have never seen my computer explode.  What should I type to see that?

**Comment by benediktahrens** [comment]
On 02/22/2016 03:49 PM, Daniel R. Grayson wrote:
> I have never seen my computer explode.  What should I type to see that?

Execute the now-commented

Time Eval vm_compute in nil natHSET.

at the end of

CategoryTheory/colimits/polynomialfunctors.v

**Pull request merged**
