### PR TITLE
Reorganization

### PR DESCRIPTION
**Pull request by DanGrayson**
this resolves issue #243

### CODE REVIEW

**Comment by benediktahrens** [comment]
ok

**Comment by vladimirias** [comment]
I suggest to put the files Associativity and Commutativity together and call the resulting file SequenceProducts.

**Comment by DanGrayson** [comment]
Okay, but maybe it should resemble BinaryOperations more, so SequenceOperations?

**Comment by vladimirias** [comment]
I am not sure that it is the right name. We do not introduce sequence operations there as a primitive notion, but only as iterated binary operations.

**Comment by DanGrayson** [comment]
How about IteratedBinaryOperations?

On Sat, Dec 5, 2015 at 3:52 PM, Vladimir Voevodsky <notifications@github.com

**Comment by vladimirias** [comment]
This sounds good.

**Comment by DanGrayson** [comment]
The error travis found was due to a pull request being granted that didn't contain the same renaming in a new file.  All should be well now ...

**Pull request merged**
