### PR TITLE
missing coherence proof for symmetric diagonal

### PR DESCRIPTION
**Pull request by rmatthes**
but there are still small holes

### CODE REVIEW

**Comment by nmvdw** [comment]
Awesome! I can fill in the parts where it is an instance of coherence of monoidal categories.

**Comment by nmvdw** [comment]
I submitted a PR to your branch. I proved all admits that were an instance of the monoidal coherence theorem. Only `inner_swap_composite_third_arg` is left.

**Comment by rmatthes** [comment]
I would be glad for help. But please keep marks where the ordinary coherence stuff would kick in - where I stopped.

**Comment by rmatthes** [comment]
Thanks to the rapid help by @nmvdw, this PR is now complete, and no more `Admitted` remains in the whole file.

**Pull request merged**
