### PR TITLE
remove -utf8 option from coqdoc command

### PR DESCRIPTION
**Pull request by DanGrayson**
resolve issue #129

### CODE REVIEW

**Comment by benediktahrens** [comment]
Do you understand why this works?
If not, I would prefer asking a question about the deactivation of pretty-printing on Coq-club over using this hack.
Can we postpone this until then?

**Comment by DanGrayson** [comment]
No, I don't understand it, because the usage message says this about the utf8 option:
```
  --utf8               set UTF-8 input language
```
We can postpone it while you inquire.

**Comment by benediktahrens** [comment]
I had a superficial look at the coqdoc source code. Below are some of the functions involved:

in tools/coqdoc/main.ml, 

| ("-utf8" | "--utf8") :: rem ->
        Cdglobals.set_utf8 (); parse_rec rem

which sets, in tools/coqdoc/cdglobals.ml

let set_utf8 () =
  charset := "utf-8";
  inputenc := "utf8x";
  utf8 := true

In tools/coqdoc/output.ml, we translate to Unicode when utf8 is true:

let initialize_tex_html () =
  let if_utf8 = if !Cdglobals.utf8 then fun x -> Some x else fun _ -> None in
  let (tree_latex, tree_html) = List.fold_right (fun (s,l,l') (tt,tt') ->
      (Tokens.ttree_add tt s l,
       match l' with None -> tt' | Some l' -> Tokens.ttree_add tt' s l'))
      [ "*" ,  "\\ensuremath{\\times}", if_utf8 "×";
        "|", "\\ensuremath{|}", None;
        "->",  "\\ensuremath{\\rightarrow}", if_utf8 "→";
        "->~",  "\\ensuremath{\\rightarrow\\lnot}", None;
        "->~~",  "\\ensuremath{\\rightarrow\\lnot\\lnot}", None;
        "<-",  "\\ensuremath{\\leftarrow}", None;
        "<->", "\\ensuremath{\\leftrightarrow}", if_utf8 "↔";
        "=>",  "\\ensuremath{\\Rightarrow}", if_utf8 "⇒";
        "<=",  "\\ensuremath{\\le}", if_utf8 "≤";
        ">=",  "\\ensuremath{\\ge}", if_utf8 "≥";
        "<>",  "\\ensuremath{\\not=}", if_utf8 "≠";
        "~",   "\\ensuremath{\\lnot}", if_utf8 "¬";
        "/\\", "\\ensuremath{\\land}", if_utf8 "∧";
        "\\/", "\\ensuremath{\\lor}", if_utf8 "∨";
        "|-",  "\\ensuremath{\\vdash}", None;
        "forall", "\\ensuremath{\\forall}", if_utf8 "∀";
        "exists", "\\ensuremath{\\exists}", if_utf8 "∃";
        "Π", "\\ensuremath{\\Pi}", if_utf8 "Π";
        "λ", "\\ensuremath{\\lambda}", if_utf8 "λ";
        (* "fun", "\\ensuremath{\\lambda}" ? *)
      ] (Tokens.empty_ttree,Tokens.empty_ttree) in
  token_tree_latex := tree_latex;
  token_tree_html  := tree_html


On the other hand, omitting --utf8 will result in a wrong html header, see function header () in output.ml .

**Comment by DanGrayson** [comment]
Then all we have to do, in addition to removing --utf8, is to add --charset utf-8, to get the character
set correct in the html.  Does that work?

For consistency, if coqdoc can output → instead of -> optionally, than coqtop should be able to do
the same on input.

**Comment by DanGrayson** [comment]
No, we're also using the option ```--with-header util/enhanced-doc/header.html```, which overrides the function header () in output.ml.

**Comment by DanGrayson** [comment]
... so nothing further is needed : the charset is always utf-8, no matter what.

**Comment by benediktahrens** [comment]
Actually, we are using those custom headers when making the enhanced html (with toggable proofs), but we are using the standard headers when doing "make html", i.e., when producing the standard html.

But anyway, browsers can generally cope with wrong information in the header, so we just simply use your suggested solution.

**Comment by DanGrayson** [comment]
I think we make only the enhanced version, with "make doc".  But I have added the
charset option to the Makefile in the recent commit, which will be better, anyway.

How about that?

**Comment by benediktahrens** [comment]
Perfect, thanks a lot!

**Pull request merged**
