### PR TITLE
coq_makefile does not generate .v.d files.

### PR DESCRIPTION
**Pull request by SkySkimmer**
This is for coq/coq#6217 which may yet be changed, so don't merge yet.
OTOH this is a good time to comment on both this PR and the Coq one ;)

### CODE REVIEW

**Comment by DanGrayson** [comment]
@SkySkimmer - it would be great if you can add your photo and some information about yourself to your github profile, so we could get to know each other.

**Comment by SkySkimmer** [comment]
Coq side got merged.

**Comment by DanGrayson** [comment]
See also https://github.com/UniMath/UniMath/issues/845

**Comment by DanGrayson** [comment]
I guess we have to also add `*.d` to the file `UniMath/.gitignore`.

**Comment by DanGrayson** [comment]
It might be cleaner to just wait until Coq 8.8 comes out, and then adapt to it, turning our backs on Coq 8.7.  In other words, the Makefile would be cleaner if it were compatible with just the latest official release of Coq.

**Comment by SkySkimmer** [comment]
>It might be cleaner to just wait until Coq 8.8 comes out, and then adapt to it, turning our backs on Coq 8.7. In other words, the Makefile would be cleaner if it were compatible with just the latest official release of Coq.

That would mean you can't be tested in Coq's CI.

**Comment by DanGrayson** [comment]
Right, I take that back.  We recently decided we don't have to keep up with old versions of Coq, but we should keep up with the current development version of Coq, in addition to the most recent stable release.

What does "CI" mean?

Have the UniMath tests for Coq already started failing?

**Comment by SkySkimmer** [comment]
>What does "CI" mean?

Continuous Integration, basically automated testing.

>Have the UniMath tests for Coq already started failing?

Yes.

**Comment by DanGrayson** [comment]
@benediktahrens - I should pull this as soon as travis gives the okay.

**Comment by benediktahrens** [comment]
@SkySkimmer : We are, in general, very grateful for the help the Coq developers have given us in the past, and specifically very grateful for your help right now in keeping UniMath in Coq's CI.

Thanks a lot!

**Comment by benediktahrens** [comment]
On 12/18/2017 10:09 PM, Daniel R. Grayson wrote:
> @benediktahrens - I should pull this as soon as travis gives the okay.
> 

Absolutely - thanks a lot!

**Pull request merged**
