### PR TITLE
make the directory on monads a bit cleaner

### PR DESCRIPTION
**Pull request by rmatthes**
For the moment, no new mathematical development, but a lot about using only "data" instead of the full structure as prerequisites for many constructions.

The currently last commit (bbb68c) is the most substantial in that it changes the structure of the Kleisli triples so that they are a proper instance of relative monads. This will be crucial for generalizations of the respective results to those relative monads.

### CODE REVIEW

**Comment by rmatthes** [comment]
@maggesi : I found K and M good for distinguishing the two worlds when the variables stood always for the entire structures, but with the coercion to the underlying functor (which used to be a parameter in your formalization), I was not bold enough to give up the well-beloved letter T for that functor. Thank you for not seeing an obstacle with this.

**Comment by rmatthes** [comment]
In order to substantiate my claim that it would help for generalization if the definitions were compatible, I redid the material of KTriples.v for relative monads. Of course, there is nothing analogous to μ. I also tried to check when "data" is sufficient - in particular if functor_data is enough for J.

**Comment by rmatthes** [comment]
It seems that the Travis checking itself has problems.

**Comment by rmatthes** [comment]
In order to substantiate my claim that it would help for generalization if the definitions were compatible, I redid the material of KleisliCategory.v for relative monads (the construction of the Kleisli category had already been in the file).

This should be enough for now. Please pull.

**Comment by rmatthes** [comment]
I identified a problem with the make process (I had not tested doing a fresh compilation). This should now be okay.

**Comment by rmatthes** [comment]
The current Travis checks already failed due to timeout when cloning Coq. Will this doom my PR?

**Comment by DanGrayson** [comment]
No, let's try to figure out why it failed.

**Comment by DanGrayson** [comment]
Here is what failed:
```
+ git submodule update --init sub/coq
Submodule 'sub/coq' (https://github.com/coq/coq.git) registered for path 'sub/coq'
Cloning into 'sub/coq'...
fatal: unable to access 'https://github.com/coq/coq.git/': Failed to connect to github.com port 443: Connection timed out
fatal: clone of 'https://github.com/coq/coq.git' into submodule path 'sub/coq' failed
```

**Comment by DanGrayson** [comment]
I've restarted the job that failed.

**Comment by DanGrayson** [comment]
That worked this time.

**Pull request merged**
