### PR TITLE
Draft license and copyright

### PR DESCRIPTION
**Pull request by DanGrayson**
for your consideration

### CODE REVIEW

**Comment by benediktahrens** [comment]
ok from A,K,S

**Comment by vladimirias** [comment]
I suggest that we change: "This copyright and license notice shall be included in all copies or
+  substantial portions of the Software" to make it read "This copyright and license notice as well as the paragraph about the UniMath development team shall be included in all copies or
+  substantial portions of the Software"

**Comment by DanGrayson** [comment]
I purposely left the paragraph about the membership of the team out of the text to be copied, because we may want to change the membership of the team from time to time.  It would be bad if the membership changed, and we edited the README file to change it, but then many copied statement with conflicting information remained out there in the world.

How about instead including a link in the copyright notice to our github site stating that the membership list is always visible there?

I have a second suggestion: let's put the license and copyright information in a separate file called "LICENSE".  Then that makes it much easier for others to propagate the text of it, since all they have to do is to propagate the file.

**Comment by vladimirias** [comment]
I think this is Ok. There will be many copies of this header (about the development team and the license and copyright) in the world. They will differ in the composition of the development team section depending on when a particular transaction involving taking a part of UniMath was made.

In fact, I am not even sure how it should look like in practice. Suppose that I want to copy some code from UniMath for my own use (say after modification). Where will I have to put the copy of the “header” (with or without the team composition info)?

**Comment by DanGrayson** [comment]
I still think it's best to have the team membership info in one place only.  Actually, some of those who copy UniMath will copy LICENSE as well as README, so they will get both bits of information.

Someone who copies 1000 lines and puts it all into one file would be free to add the LICENSE to the same file.  Or they could make two files and put them in the same subdirectory, with an indication somewhere that the 1000 lines are governed by the LICENSE file.

**Comment by vladimirias** [comment]
Ok.

**Comment by DanGrayson** [comment]
I've made the changes discussed above, so perhaps we are almost ready to accept them.

**Comment by vladimirias** [comment]
LGTM

**Comment by benediktahrens** [comment]
lgtm

Am 4. Juli 2015 18:25:54 MESZ, schrieb "Daniel R. Grayson" <notifications@github.com>:

**Pull request merged**
