### PR TITLE
replaces v3 by v4 in all actions (this should do the migration from N…

### PR DESCRIPTION
**Pull request by rmatthes**
…ode 16 to Node 20)

### CODE REVIEW

**Comment by rmatthes** [comment]
I did not dig deeper into the .yml file. I only applied the changes to one of the three files for the moment. I am surprised that the macOS build does not profit from the cache while the other checks are as successful or unsuccessful as before, seen in max. 2 minutes.

**Comment by benediktahrens** [comment]
@rmatthes : thanks a lot for preparing this! For my education, could you point me to a resource explaining what you briefly mention about "nodes"? Relatedly, is there a way to receive updates about new versions of the scripts?

**Comment by rmatthes** [comment]
@benediktahrens I just followed warnings and fell on https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ . This is not an organized way to keep track of version updates.

**Review by benediktahrens — APPROVED** [review]
It looks fine to me, but I am not competent. It would be great to have @m-lindgren 's feedback.

**Comment by rmatthes** [comment]
Changing the language versions triggers a full rebuild. The satellites are not touched by this since their CI has not yet been updated (see the pending PR in the repos).

**Review by m-lindgren — APPROVED** [review]
Looks good to me!

**Pull request merged**
