### PR TITLE
update INSTALL to use coq 4.02.3

### PR DESCRIPTION
**Pull request by DanGrayson**

### CODE REVIEW

**Comment by palmskog** [comment]
This looks good. 

Just to clarify my worry about `lablgtk` dependencies. On Ubunty, `opam install lablgtk` fails if one has not run `sudo apt-get install libgtk2.0-dev` first, i.e., one has to install the GTK 2 header files via the system package manager. On Mac OS X, can one be sure that these header files are always present? Maybe someone with Mac OS X can confirm that this is the case, or refer to some `brew` package for GTK 2 headers? I'm not very Mac savvy myself.

**Comment by DanGrayson** [comment]
Oh, thanks.  It seems I have install gtk2 using brew, so I've just updated the pull request.  See https://github.com/UniMath/UniMath/pull/807/commits/9268cd7a194a50af179a1381fe87db9b2eb2235b

**Comment by DanGrayson** [comment]
@benediktahrens , we should pull this before the workshop

**Comment by benediktahrens** [comment]
On 12/10/2017 03:25 PM, Daniel R. Grayson wrote:
> @benediktahrens <https://github.com/benediktahrens> , we should pull 
> this before the workshop

I am merging it, but the instructions for Company-Coq should really be 
somewhere else - they are adding noise to what should be a very compact 
installation guide.

**Comment by benediktahrens** [comment]
On 12/10/2017 03:25 PM, Daniel R. Grayson wrote:
> @benediktahrens <https://github.com/benediktahrens> , we should pull 
> this before the workshop


More specifically, we should first have a section on everything 
necessary to compile UniMath, and then a section on useful, but 
non-essential helper tools (such as company-coq).

**Pull request merged**
