### PR TITLE
Focussing for tactics in topology and RealNumbers

### PR DESCRIPTION
**Pull request by nmvdw**
This PR guarantees that all goals in Topology are properly focussed

### CODE REVIEW

**Comment by nmvdw** [comment]
Seems like RealNumbers depends on Topology, so RealNumbers has to be fixed as well now

**Comment by nmvdw** [comment]
Note: AlgebraicGeometry imports `Topology`, so that package is fine as well

**Comment by nmvdw** [comment]
Paradoxes is fine now as well

**Comment by nmvdw** [comment]
Fixing folds is quick as well

**Review by rmatthes — APPROVED** [review]

**Pull request merged**
