### PR TITLE
Updated version of #1822

### PR DESCRIPTION
**Pull request by benediktahrens**
This PR is an updated version of #1822

### CODE REVIEW

**Comment by benediktahrens** [comment]
Merging this now without waiting for the macOS build.

**Comment by proux01** [comment]
@DenSinH @nmvdw @benediktahrens merging this PR broke Coq CI (see for instance https://github.com/coq/coq/pull/18713 that ran yesterday). The compilation of files UniMath/ModelCategories/Generated/LNWFSClosed.v and UniMath/ModelCategories/Generated/LNWFSClosed.v is very slow (multiple dozen minutes) and triggers the 1h timeout there. We are going to exclude package ModelCategories from Coq CI unless you have a better solution.

**Comment by nmvdw** [comment]
I agree with your solution. We put ModelCategories in a separate package for that purpose.

**Comment by nmvdw** [comment]
> The compile times are due to some changes I had to make for this package to work with the recent changes in UniMath. If I recall correctly, the definitions for monads have changed slightly, and those for comonads have been added. These are apparently significantly slower somehow...

I see. Such changes might require some minor refactoring at some other parts.

**Pull request merged**
