### PR TITLE
Added complexes

### PR DESCRIPTION
**Pull request by tpannila**
This PR contains definition of (cochain) complexes. The following two results are proved
- The category of complexes over an additive precategory is an additive precategory,
  ComplexPreCat_Additive, line 1199, Complexes.v
- The category of complexes over an abelian precategory is an abelian precategory,
  ComplexPreCat_AbelianPreCat, line 1885, Complexes.v

Suggestions for improvements are welcome.

Tomi

### CODE REVIEW

**Comment by vladimirias** [comment]
First of all wow! This is a an impressive step.

Here are two ideas:

1. make Cob : Complex -> ( hz -> Ob A ) into a coercion from complexes to Funclass.

2. Call CMor by diff (the differential) and make the Complex argument of it implicit.

**Comment by vladimirias** [comment]
I also see more constructions (Definition, Lemma etc.) that can have many of the arguments (often all Complex arguments) to be made implicit because they are easily computed by Coq based on other arguments. And you can always use @ in front of an identifier if you need to give all arguments explicitly.

**Comment by tpannila** [comment]
I did the stuff you suggested. 

I started to work towards the naive homotopy category K(A), 
https://en.wikipedia.org/wiki/Homotopy_category_of_chain_complexes ,
https://en.wikipedia.org/wiki/Derived_category , and I think I managed to do it.
The code is bad. I pushed just to have an online backup of the changes. I begin to 
recheck, add more comments, and clean the code tomorrow.

Tomi

**Comment by vladimirias** [comment]
Tomi, don’t you have your own fork of the UniMath on GitHub where you can upload your work without having to send it directly to UniMath/UniMath?

**Comment by tpannila** [comment]
Yes, I could have moved the changes to other branch. Anyway, I cleaned, 
rechecked, and added a few comments. The construction of K(A) should 
be correct.

Tomi

**Comment by tpannila** [comment]
I added cohomology functor, see CohomologyComplex.v. For some reason construction of translation
functor does not terminate, see line 2343 of Complexes.v. How to fix it?

Tomi

**Comment by vladimirias** [comment]
LGTM I will look at the translation functor problem after we merge and I can pull the whole thing to my fork.

**Comment by tpannila** [comment]
Resolved the conflicts.

**Pull request merged**
