### PR TITLE
issue 1576 implemented differently

### PR DESCRIPTION
**Pull request by rmatthes**
- Require Export UniMath.Tactics.EnsureStructuredProofs. should appear in the files that are root of a dependency tree
- modifies the previous treatment of SubstitutionSystems and Bicategories 
- applies the treatment to package PAdics
- the PAdics files were partly in DOS encoding, now in sync with the rest - can irritate diff tools (the tool meld copes with this well)

### CODE REVIEW

**Review by nmvdw — APPROVED** [review]

**Comment by nmvdw** [comment]
```
error: *** UniMath/PAdics/lemmas.vo should not require UniMath/Tactics/EnsureStructuredProofs.vo
[35](https://github.com/UniMath/UniMath/actions/runs/3332521688/jobs/5513490860#step:4:36)
error: *** UniMath/Bicategories/Core/Bicat.vo should not require UniMath/Tactics/EnsureStructuredProofs.vo
[36](https://github.com/UniMath/UniMath/actions/runs/3332521688/jobs/5513490860#step:4:37)
2 dependency order errors in package listings
```
I'm surprised by these errors. For the remainder the PR looks good.

**Comment by rmatthes** [comment]
Sorry for not having checked this - I had only compiled the library before the commit.

**Comment by nmvdw** [comment]
It seems like we first need to implement this change in the relevant subrepositories, because now the error is at `TypeTheory`.

**Comment by benediktahrens** [comment]
@nmvdw @rmatthes : if I understand correctly, @nmvdw is suggesting a change (simplification) to UniMath and TypeTheory. This suggestion is currently only in the comment to a merged PR. Could you file issues to the relevant repositories, pointing to the comment above?

**Pull request merged**
