### PR TITLE
Limits

### PR DESCRIPTION
**Pull request by benediktahrens**
Limits as duals of colimits
some specific limits:
* products
* pullbacks

### CODE REVIEW

**Comment by mortberg** [comment]
I think we should add:

Arguments f : simpl never.

for all definitions f in limits, and in all of the files that are implemented using limits or colimits. This will make sure that simpl don't unfold too much and show the underlying implementation to the user which will make these definitions more pleasant to work with. 


We should also change three in pullbacks to "unit + unit + unit" or some other finite set with 3 elements...

**Comment by benediktahrens** [comment]
On 10/26/2015 10:42 PM, Anders Mörtberg wrote:
> I think we should add:
> 
> Arguments f : simpl never.
> 
> for all definitions f in limits, and in all of the files that are
> implemented using limits or colimits. This will make sure that simpl
> don't unfold too much and show the underlying implementation to the
> user which will make these definitions more pleasant to work with.

Good idea!

> We should also change three in pullbacks to "unit + unit + unit" or
> some other finite set with 3 elements...

We will need a layer on top of that to make programming with it
convenient, that is, to simulate the induction principle of our type
"three".

**Comment by DanGrayson** [comment]
Yes:
```
Inductive three := One | Two | Three.
```
goes against the guidelines.  Another suitable set would be ```stn 3```.  It's easy to
make its elements with expressions like ```stnpair 3 1 (idpath _)```.

**Comment by DanGrayson** [comment]
Another possibility would be coprod bool unit, and think of ii2 tt as being for the vertex of pushouts
and pullbacks.

**Comment by mortberg** [comment]
Yes, but defining functions by case on `stn 3` is quite painful. I tried yesterday with natbooleq (or what it is called) and if-then-else, but the proofs got much longer and I gave up. I think using `bool + unit` could be easier, but I will have to try. 

Something that would be cool would be to have a dependently typed function that gives you the recursor for `stn n` (we need dependent types as the arity will depend on n).

**Comment by mortberg** [comment]
I didn't see your second reply before replying, but we are thinking along the same lines.

**Comment by DanGrayson** [comment]
No, defining a function on stn 3 is not so bad:

```

Definition three_cases {X} (a b c : X) : stn 3 -> X.
Proof.
  intros ? ? ? ? [i lt].
  induction i.
  - exact a.
  - induction i.
    * exact b.
    * induction i.
      + exact c.
      + simpl in lt. induction (nopathsfalsetotrue lt).
Defined.

Goal stnsum (three_cases 4 5 6) = 15. reflexivity. Qed.
```

**Comment by DanGrayson** [comment]
We could get rid of four inductive definitions by replacing empty by stn 0,
unit by stn 1, bool by stn 2, and coprod by total2 over bool.

**Comment by mortberg** [comment]
Ok, not too bad. But then when I do proofs I need to do a bit of extra work to expose the underlying nats to do induction on them (this work is trivial but tedious). For `stn 3` this is ok, but imagine doing it for a bigger n...  I think the best would be to define the recursor and then prove a general induction lemma for `stn n`. Maybe something to try for UniMath day.

**Comment by DanGrayson** [comment]
How about just packaging up introduction and elimination for a three
element type "three", implemented
with stn 3, and with proofs locked under Qed so you never have to see the
numbers?  I could try that
exercise.

**Comment by mortberg** [comment]
Do that if you want to, I could also do it. For this problem `bool + unit` might still be easier to work with though. Anyway this will be a good test to see if `stn 3` or `bool + unit` is easier to work with (ie which one gives the simplest and shortest definitions and proofs).

**Comment by benediktahrens** [comment]
On 10/27/2015 10:16 AM, Anders Mörtberg wrote:
> Do that if you want to, I could also do it. For this problem `bool +
> unit` might still be easier to work with though. Anyway this will be
> a good test to see if `stn 3` or `bool + unit` is easier to work with
> (ie which one gives the simplest and shortest definitions and
> proofs).

If you are against three (which I am), you should also be against bool,
as it is the same: an inductive datatype - see #197 .
So replacing three by bool + unit is not solving the issue.

One could still argue that having only bool is better than having bool
and three, but in my opinion, that tiny advantage does not justify the
hassle of defining three = bool + unit.

So, put differently, if you want to eliminate three, please also
eliminate bool.


I am not very familiar with the parts of Foundations that use bool, but
I fear that it might be a gigantic undertaking.

**Comment by mortberg** [comment]
Getting rid of bool seems like an incredibly painful endeavour and nothing I want to work on. I think it makes sense to remove three now as we are just adding new stuff. Removing bool will require much more work as it is used everywhere, while three is only used in one file. So lets keep three for now and then get rid of it once Dan has packaged `stn 3` nicely?

**Comment by DanGrayson** [comment]
If we could figure out how to get Coq to have "induction" call something we
make
by hand, as Anders has told me is possible, then replacing "bool", "unit",
"empty",
and "coprod" would all be easy.

**Pull request merged**
