### PR TITLE
Adapt to https://github.com/coq/coq/pull/18880

### PR DESCRIPTION
**Pull request by proux01**
Adapt to https://github.com/coq/coq/pull/18880

This is strictly equivalent but avoids a warning / error.

### CODE REVIEW

**Comment by proux01** [comment]
CI green

**Review by nmvdw — APPROVED** [review]

**Comment by proux01** [comment]
Thanks!

**Comment by benediktahrens** [comment]
@proux01 : Thanks for filing this PR and help keeping UniMath compatible with Coq!

**Comment by benediktahrens** [comment]
Does `Parameter` yield an axiom? The documentation seems to say so: https://coq.inria.fr/doc/V8.19.0/refman/language/core/assumptions.html#coq:cmd.Parameter

In this case, we do not want `Parameter`.

**Comment by rmatthes** [comment]
This means the file had been wrong before. The contents should have been inside a section.

**Comment by SkySkimmer** [comment]
This PR fixes the parts tested in coq CI but there are also occurrences in the rest of unimath, eg https://github.com/UniMath/UniMath/blob/6f25862d5778b4c9775a6c3ba9ad9fae5dd9427a/UniMath/ModelCategories/Examples.v#L24

**Comment by proux01** [comment]
Of course, but not my reponsibility to fix them (we could already argue whether I had to fix the other ones in the first place).

**Comment by nmvdw** [comment]
> This PR fixes the parts tested in coq CI but there are also occurrences in the rest of unimath, eg
> 
> https://github.com/UniMath/UniMath/blob/6f25862d5778b4c9775a6c3ba9ad9fae5dd9427a/UniMath/ModelCategories/Examples.v#L24

Yes. This is the reason why the CI for coq dev in #1888 . They are fixed now.

**Pull request merged**
