### PR TITLE
Primitive projections

### PR DESCRIPTION
**Pull request by DanGrayson**
We change the definition of "total2" from an inductive definition to a record and make some trivial
changes to get UniMath to work with primitive projections.  (One advantage of turning on primitive
projections is eta expansion for pairs.)  Most changes involve replacing "apply" by "refine", which
works better.  Some changes involve working around failures of "fold".

We don't completely succeed in working around all the problems, but the Foundations package
compiles completely.  The current obstacle is in the Ktheory package.

It's worthwhile checking this in now to incorporate the changes into our development, allowing
others to experiment with primitive projections, and relieving me of the need to maintain the branch,
for the time being.  To experiment, just uncomment the command "Set Primitive Projections" in
Preamble.v.

This represents partial progress on #111

### CODE REVIEW

**Comment by benediktahrens** [comment]
You say 'Most changes involve replacing "apply" by "refine", which
works better.'. What does "better" mean here? You mean that one works while the other doesn't?

**Comment by DanGrayson** [comment]
Yes, "refine" works better because it works more often.

**Comment by benediktahrens** [comment]
On 12/23/2015 08:23 AM, Daniel R. Grayson wrote:
> Yes, "refine" works better because it works more often.

So all the replacements of "apply H" by "refine (H _ _ _ _ )" that you
did in this PR were necessary?

**Comment by mortberg** [comment]
Is it just me or isn't it very painful to have to write "refine (H _ _ _ _ _)" instead of simply "apply H"? It is very annoying when Coq develops in the wrong direction... 

Maybe we could make a tactic "rapply H" that tries "refine H | refine (H _) | refine (H _ _) | ..." so that one doesn't have to guess the number of implicit arguments all the time?

**Comment by DanGrayson** [comment]
Yes, every replacement of apply by refine was necessary.  "Apply" is sort of buggy.

In "refine (H _ _ _)" the blanks represent explicit arguments.  But often "apply" does work.

**Comment by DanGrayson** [comment]
Unless we switch to primitive projections, none of you will have the pain of having to write
"refine (H _ _ _ _ _ )", for "apply" will probably continue to work more often.

**Comment by benediktahrens** [comment]
On 12/23/2015 03:20 PM, Daniel R. Grayson wrote:
> Yes, every replacement of apply by refine was necessary.  "Apply" is
> sort of buggy.

Is there a bug report on that? Is Matthieu aware of that problem?

**Comment by DanGrayson** [comment]
It might have been Matthieu who told me...

**Comment by mortberg** [comment]
Oops, I meant explicit arguments instead of implicits. Anyway I still really don't like to always write all these underscores...

**Comment by benediktahrens** [comment]
What should we do with this PR? To summarize what I have understood:
If we pull it, then we might end up having to use refine instead of apply in many places.
But if we ever want to have eta for pairs, there is no way around this change. 
Is that correct?

**Comment by DanGrayson** [comment]
No, that's not right.  Primitive projections are not turned on by this PR, because I couldn't fix everything, so you can keep coding new code as you did before, with refine instead of apply; I think I didn't say that clearly.  Notice that all the tests have passed.

But yes, if we ever want to use eta for pairs, these changes must be made, so it seems highly desirable to go ahead, so as to incorporate the work already done in that direction.

By the way, Matthieu gave some further hints about speeding things up when primitive projections are on, which I will ultimately implement.

**Comment by benediktahrens** [comment]
On 01/19/2016 09:56 AM, Daniel R. Grayson wrote:
> No, that's not right.  Primitive projections are not turned on by
> this PR, because I couldn't fix everything, so you can keep coding
> new code as you did before, with refine instead of apply; I think I
> didn't say that clearly.  

That's whay I meant: even without primitive projections, but only using
a Record for total2 instead of an Inductive, we need to replace some
"apply" with "refine".
Right?

> Notice that all the tests have passed.

There's a merge conflict now, unfortunately.

> But yes, if we ever want to use eta for pairs, these changes must be
> made, so it seems highly desirable to go ahead, so as to incorporate
> the work already done in that direction.
> 
> By the way, Matthieu gave some further hints about speeding things up
> when primitive projections are on, which I will ultimately
> implement.

Brilliant. If you share those hints with us, we can maybe help.

**Comment by DanGrayson** [comment]
No, this PR leaves "total2" as an inductive type.

To see Matthieu's suggestions, click on the second bug report link in my comment at https://github.com/UniMath/UniMath/issues/111#issuecomment-155904433

**Comment by DanGrayson** [comment]
I fixed the merge conflicts.

**Pull request merged**
