### PR TITLE
Reorganize foundations, part 1

### PR DESCRIPTION
**Pull request by DanGrayson**
Here we set the stage for reorganization of Foundations as envisioned in issue #350 

  Basics < Combinatorics < Algebra < NumberSystems

I.e., no file should require one from a subdirectory occurring later than its
own on this list.

To accomplish this we moved the basic material about natural numbers
not depending on Algebra into Basics and put the other material into
a new file called NumberSystems/NaturalNumbersAlgebra.v.

### CODE REVIEW

**Comment by DanGrayson** [comment]
https://github.com/UniMath/UniMath/pull/539/commits/7aac82ff4377d029b2f106516fd768836d6f5849 enforces linear ordering of proof files.

**Comment by benediktahrens** [comment]
@DanGrayson : Oh no, a conflict...

**Comment by DanGrayson** [comment]
Okay.  Guess what: the new file eqdiag.v depends on something in Ktheory, so I'll move some lemmas to fix that.

**Comment by benediktahrens** [comment]
How did you notice that? Has your new make target made you aware of that?

**Comment by DanGrayson** [comment]
Yes, when it said that eqdiag.v should not depend on Ktheory/Utilities.

**Comment by benediktahrens** [comment]
On 01/13/2017 05:47 PM, Daniel R. Grayson wrote:
> Yes, when it said that eqdiag.v should not depend on Ktheory/Utilities.

Can one see that somewhere?

**Comment by DanGrayson** [comment]
It was on just my screen, but you can try it: put back the Require that used to be in eqdiag.v and type make on the current master branch.

**Comment by DanGrayson** [comment]
I will have the next pull request soon.  Testing ...

**Pull request merged**
