### PR TITLE
Update Rigs_and_Rings.v

### PR DESCRIPTION
**Pull request by AnthonyBordg**
This PR adds `isaset_rngfun`.

### CODE REVIEW

**Comment by DanGrayson** [comment]
lgtm

**Comment by DanGrayson** [comment]
Why such a complicated history to add a single lemma?

**Comment by AnthonyBordg** [comment]
@DanGrayson : from the very beginning I made the mistake to change the master branch of my fork (which I guess should never change or only to be updated with respect to the master branch of UniMath), hence it is ahead of UniMath causing sometimes conflicts before a pull request that need to be solved.

**Comment by siddharthist** [comment]
@DanGrayson There is an option on Github to "squash" the commits in a pull request (click the drop-down arrow on the button "Merge pull request" to see this). Once this passes Travis, it can be merged that way (this is helpful when one has contributors who are less experienced with Git, you don't have to ask them to clean their commit history as much).

**Pull request merged**
