### PR TITLE
Update Coq submodule to 8.16.1

### PR DESCRIPTION
**Pull request by m-lindgren**
This updates the Coq submodule to version `8.16.1` from `8.15.2`.

`8.16.1` includes many quality of life improvements in particular to coercions and has been tested extensively and in use for some time now.

This should fix this [build error](https://github.com/UniMath/UniMath/actions/runs/4422241576/jobs/7753857350) which occurs with `make BUILD_COQ=yes`.

### CODE REVIEW

**Review by benediktahrens — APPROVED** [review]

**Comment by benediktahrens** [comment]
@m-lindgren : Thanks a lot!

**Comment by DanGrayson** [comment]
By the way, "dagger category" is a ridiculous name.

**Comment by nmvdw** [comment]
> By the way, "dagger category" is a ridiculous name.

Unfortunately, it seems to be standard in the literature (eg, in https://homepages.inf.ed.ac.uk/cheunen/publications/2016/dagger/dagger.pdf), and one can't start an identifier in Coq with † (†-category would be the alternative name).

**Comment by m-lindgren** [comment]
Not sure who called it "dagger category" first or why they preferred that name instead of "category with involution" or "involutive category".

**Pull request merged**
