### PR TITLE
 Show that under some circumstances, two precomposition functors that together are an adjoint equivalence, are also themselves adjoint equivalences

### PR DESCRIPTION
**Pull request by arnoudvanderleer**

### CODE REVIEW

**Review by benediktahrens — APPROVED** [review]
This code looks good. Should it be in package `CategoryTheory` instead of `AlgebraicTheories`?

**Comment by arnoudvanderleer** [comment]
> This code looks good. Should it be in package `CategoryTheory` instead of `AlgebraicTheories`?

Thanks. And yes, I suppose so. Just in the root directory, or maybe in Equivalences?

**Comment by benediktahrens** [comment]
> > This code looks good. Should it be in package `CategoryTheory` instead of `AlgebraicTheories`?
> 
> Thanks. And yes, I suppose so. Just in the root directory, or maybe in Equivalences?

@nmvdw ?

**Comment by nmvdw** [comment]
> > This code looks good. Should it be in package `CategoryTheory` instead of `AlgebraicTheories`?
> 
> Thanks. And yes, I suppose so. Just in the root directory, or maybe in Equivalences?

In Equivalences it would fit quite well, right? Throwing everything in the root directory makes the root directory messy

**Pull request merged**
