### PR TITLE
Introduce vocabulary "univalence" for categories

### PR DESCRIPTION
**Pull request by benediktahrens**
Rename
- `is_category` -> `is_univalent`
- `category` -> `univalent_category`

### CODE REVIEW

**Comment by mortberg** [comment]
lgtm

Will you also rename precategory -> category? Maybe this will go into another PR?

**Comment by benediktahrens** [comment]
On 05/04/2017 10:49 PM, Anders Mörtberg wrote:
> lgtm
> 
> Will you also rename precategory -> category? Maybe this will go into another PR?

You mean Precategory -> category ?

I am slightly weary about that. I am thinking about reserving the word
"category" for informal discussion and comments, i.e., for the union of
all the notions of categories in UniMath.

But I haven't had a good idea for a word to replace "Precategory".

I'd be very grateful for any suggestions.

Renaming "Precategory" should probably go in a different PR. At least to
me, the present one is very uncontroversial, whereas replacing
"Precategory" is more difficult.

**Comment by mortberg** [comment]
Yes, that's what I meant. I updated my comment directly after sending it, but I guess that isn't reflected in the email sent out to everyone watching the library.

I like the name "category" for what we now call "Precategory". I think it is the closest to what people normally mean by the word "category" so it makes perfect sense to me to use it in our formalization. Maybe this should be discussed in a separate issue though and not here, as you say this PR should be very uncontroversial in its current form while renaming Precategory requires some discussion.

**Comment by DanGrayson** [comment]
... *wary* ...

**Comment by DanGrayson** [comment]
this addresses part of #699

**Comment by benediktahrens** [comment]
On 05/04/2017 11:07 PM, Daniel R. Grayson wrote:
> ... *wary* ...
> 

Yes, that's it. Thanks :-)

**Pull request merged**
