### PR TITLE
Some theory about presheaf categories

### PR DESCRIPTION
**Pull request by mortberg**
Define the (set-valued) presheaf category Psh C as [C^op,HSET] and prove various things:

- Construction of some (co)limits (all of these are lifted from HSET to the functor category)
- Definition of the subobject classifier in Psh C as the set of sieves (there is no proof yet that this actually is the subobject classifier as this notion hasn't been defined in UniMath yet)
- Various minor results (morphisms from the terminal object are monic, morphisms to the initial object are epi and construction of the terminal object in functor categories from the target category)

### CODE REVIEW

**Comment by DanGrayson** [comment]
Looks good to me.

But why not rename Psh to Presheaf?  It would be less cryptic.

**Comment by vladimirias** [comment]
Or PreShv, this is what I use in my papers.

**Comment by vladimirias** [comment]
I want to have a look. I had some ideas on how to make b : F Y  and # F f b for f:X-->Y well typed.

**Comment by benediktahrens** [comment]
To add another variant, in UniMath/TypeTheory, we use `preShv`.

**Comment by mortberg** [comment]
I got the abbreviation from: https://ncatlab.org/nlab/show/category+of+presheaves (But as you see I changed the capitalization...)

Many books also use \hat{C} (according to MacLane/Moerdijk this is the notation of the French school, which I guess refers to the Grothendieck school). This isn't easy to type in emacs though and the best approximation I can think of is C^ which is quite ugly. 

I like Vladimir's suggestion, it's just a little longer and a lot more informative. I'm not a fan of having a lowercase p as first letter as I like having lowercase first letter for elements of a category and uppercase for categories.

**Comment by mortberg** [comment]
I renamed Psh to PreShv now and rebased on master. I think this should be ready to be merged as soon as travis is done

**Comment by DanGrayson** [comment]
Vladimir said he wants to have a look first, so let's wait for him to say something before merging.

**Comment by mortberg** [comment]
I've put this up to speed with the master branch now

**Comment by mortberg** [comment]
I just added the discrete presheaf defined by a set A. This felt too simple to put in another PR so I added it to this one.

**Comment by DanGrayson** [comment]
Isn't it called the constant presheaf?

**Comment by mortberg** [comment]
I was thinking about discrete simplicial/cubical sets. There are constant functors to Set right? So I wasn't sure if I should call it a constant or discrete presheaf?

**Comment by DanGrayson** [comment]
It's definitely called a constant presheaf, not a discrete presheaf.  Only when the category is something like Delta do we think of those things as spaces, so that a word like "discrete" would be applicable.

**Comment by mortberg** [comment]
Ok, thanks. I updated the name now.

**Comment by DanGrayson** [comment]
lgtm

**Comment by mortberg** [comment]
Maybe we could merge this PR now? It has been open for 4 weeks and it would be great to get the code into UniMath. I have some lemmas that I think could be useful for other people (e.g. Matthew Weaver), but these should go into a new PR as I don't want to make this one any bigger. I would also like to experiment with making PreShv into a definition instead of a notation so that I can add a coercion to functor and maybe get rid of all the explicit pr1's that are needed now. 

Maybe Vladimir could try out his ideas on the merged code when he has time or make an issue about it so that we don't forget and can experiment later.

**Comment by DanGrayson** [comment]
Not too long ago Vladimir emphasized to me that he still wants to take a look at this, which perhaps he will have time to do after March 25.  On the other hand, as you say, he could look at it even after the merge.  @vladimirias ?

**Comment by benediktahrens** [comment]
This PR has been around for far too long.
I suggest merging this PR and making an issue about the problem given by the need for `pr1`s.

**Comment by mortberg** [comment]
I merged master and fixed the conflicts now. I hope travis will be happy.

**Comment by benediktahrens** [comment]
lgtm

**Pull request merged**
