### PR TITLE
add notation for funcomp the other way

### PR DESCRIPTION
**Pull request by DanGrayson**
resolves issue #472

### CODE REVIEW

**Comment by benediktahrens** [comment]
lgtm

**Comment by benediktahrens** [comment]
Actually, I would like to retract my "lgtm". This symbol is barely readable. Now, some people will say that that is due to a bad font, not due to the symbol itself, but that is misleading: I cannot (easily) change font on Github, for instance.

**Comment by DanGrayson** [comment]
We have a suggestion from Anders on another thread to use ";;" instead, which seems fine to me.  Vladmir?

I want to add the \cdot stuff to this pull request, anyway.  If we adopt ";;" we may have to stop using it completely for "compose", but that won't be a problem, except for the need to update TypeTheory.

**Comment by vladimirias** [comment]
Let’s drop it for now. In Basics I may want to use another notation. For now funcomp is fine.

**Comment by vladimirias** [comment]
\cdot stuff is good to make a separate PR since we all agree on it.

**Pull request closed without merging**
