### PR TITLE
z_iso replaces iso, even beyond issue #1504

### PR DESCRIPTION
**Pull request by rmatthes**
The issue is about replacing `iso` by `z_iso` in `idtoiso`. The `iso` concept is still maintained, but the lemmas that do not compile any longer after this switch are not duplicated but only formulated for `z_iso`. 
I had the intention of migrating all of the package `CategoryTheory` in this spirit, but this promises to take more time, which is why I at least unearth this development as draft pull request.
The touched files compile, but `make -j20 UniMath/CategoryTheory/All.vo` shows five non-compiling .v-files at the time of opening this request (May 13).

### CODE REVIEW

**Comment by rmatthes** [comment]
In my [last commit](https://github.com/UniMath/UniMath/pull/1507/commits/9d5c9af) I identified the seven .v files that would still need some care. I know that `Admitted` is not acceptable in the master branch. I ask the respective authors to have a look. In case nothing depends on those elements, one could think of temporarily aborting them. This is unlikely for `Bicategories/DisplayedBicats/Examples/DispBicatOfDispCats.v` that has four descendants, for `Bicategories/DisplayedBicats/ExamplesOfCleavings/FibrationCleaving.v` and `Bicategories/DisplayedBicats/ExamplesOfCleavings/OpFibrationCleaving.v` that have two descendants each. The contents of `CategoryTheory/DisplayedCats/Constructions.v` is even imported by 44 files. The other three files are leaves in the dependency tree, (fully or as concerns the now critical part) authored by @Kfwullaert and @nmvdw , respectively.

**Comment by rmatthes** [comment]
Okay, only `Admitted` left in the "inner node" `CategoryTheory/DisplayedCats/Constructions.v` and the leaf `CategoryTheory/Monoidal/TotalDisplayedMonoidalCurried.v`.

**Comment by benediktahrens** [comment]
> Okay, only `Admitted` left in the "inner node" `CategoryTheory/DisplayedCats/Constructions.v` and the leaf `CategoryTheory/Monoidal/TotalDisplayedMonoidalCurried.v`.

@rmatthes : Thanks a lot for this PR!

Are these constructions still admitted or commented out? 

Is there anything that should be fixed before the PR is merged?

**Comment by rmatthes** [comment]
The commit after the remark of mine you cite commented them out (I have the permission of the author of the second of those files). The strings "Admitted" still appear in these files since I commented out the whole parts.
I think that it is safe to merge this PR and to think about lighter notation later (since there are now so many `_z` in the vernacular).

**Comment by benediktahrens** [comment]
It is interesting that UniMath still compiles after commenting out these constructions - they don't seem to be of great interest by themselves. Possibly they are used in satellites?

Thanks for providing the extra information, that's very helpful!

@peterlefanulumsdaine : merging this PR might entail the need for some repair work in TypeTheory. Any objections to merging now?

**Comment by rmatthes** [comment]
By the way, I already fixed the satellite largecatmodules (a pending PR)  and have done first steps towards fixing TypeTheory (only as far as B- and C-systems were concerned, see the pending PR).

**Comment by peterlefanulumsdaine** [comment]
Yep, I have no objection — I’m happy to help fix things in TypeTheory if necessary afterwards.   Thankyou @rmatthes for so much good work on this.  Re the commented bits (which as far as I can see are all in DisplayedCats/Constructions.v, is that right?) — could you file an issue noting these, so they don’t just get forgotten and decay?

**Comment by benediktahrens** [comment]
> By the way, I already fixed the satellite largecatmodules (a pending PR) and have done first steps towards fixing TypeTheory (only as far as B- and C-systems were concerned, see the pending PR).

That's fantastic - thanks a lot!

**Pull request merged**
