### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by nmvdw**
- Remove a comment
- Add results on preservation by adjunctions
- Adjunctions in bicategories of categories with some structure
- Simplify a definition
- More properties of projection functor

### CODE REVIEW

**Comment by benediktahrens** [comment]
This PR removes some code. From a quick glance, this code has not been copied elsewhere. Do you mean to remove that code?

**Comment by nmvdw** [comment]
I remove two pieces of code:
- Comments of old code that is meant to be removed. It was an old version of what’s there new
- A definition in ToCatMonad. This definition was actually duplicated, so there’s no problem with removing it.

**Comment by nmvdw** [comment]
The error is in `File "./Modules/Signatures/BindingSig.v", line 287, characters 24-62:`

I changed two files in CategoryTheory: Projection.v and Preservation.v. Neither of them are imported by that file. In addition, nothing from Bicategories is imported in `BindingSig.v`, so I don't know why this error occurs.

**Comment by benediktahrens** [comment]
I don't think that the error in `largecatmodules` is due to your changes. Let's ignore that error for the purpose of this PR.

**Comment by benediktahrens** [comment]
Addendum: the CI error in largecatmodules was already present before this PR, see https://github.com/UniMath/largecatmodules/pull/144.

**Pull request merged**
