### PR TITLE
avoids very numerous warnings about delimiting key for scope cat

### LINKED ISSUE #1791: A warning
We get the following warning

> Warning: Warning: Overwriting previous delimiting key cat in scope cat
[overwriting-delimiting-key,parsing,default]

### PR DESCRIPTION
**Pull request by rmatthes**
the scope Cat is given up and its uses replaced by either cat or no scope declaration

Resolves #1791

### CODE REVIEW

**Review by nmvdw — APPROVED** [review]

**Comment by rmatthes** [comment]
I have filed PR to correct the issues with largecatmodules and TypeTheory.

**Comment by rmatthes** [comment]
I do not know how to react to the error messages coming from Coq 8.20alpha. They appear in files I did not touch on:
- UniMath/Bicategories/DisplayedBicats/Examples/Codomain.v
- UniMath/Bicategories/OrthogonalFactorization/EsoFactorizationSystem.v

**Comment by nmvdw** [comment]
> I do not know how to react to the error messages coming from Coq 8.20alpha. They appear in files I did not touch on:
> 
> * UniMath/Bicategories/DisplayedBicats/Examples/Codomain.v
> * UniMath/Bicategories/OrthogonalFactorization/EsoFactorizationSystem.v

It seems like there was a change to a Coq version that affected some code (I don't have the developer version of Coq)

**Comment by benediktahrens** [comment]
@rmatthes : thanks for preparing these PRs! I would like to let them sit for a few days, to give people a chance to evaluate them and comment. I don't know the scope mechanism well myself.

**Comment by rmatthes** [comment]
@benediktahrens I see no dynamics - what would trigger that the PR can be merged?

**Pull request merged**
