### PR TITLE
Update files

### PR DESCRIPTION
**Pull request by jscarfy**
added Yang_n.v

### CODE REVIEW

**Comment by arnoudvanderleer** [comment]
@jscarfy Can you tell a bit about what your intentios is with this PR?

**Comment by jscarfy** [comment]
Re: more I mean this = https://github.com/jscarfy/UniMath/blob/master/UniMath/NumberSystems/Yang_n.vThanks in advance and best,-Justin On Nov 15, 2024, at 07:40, Pu Justin Yang 楊靐龘 ***@***.***> wrote:﻿Thanks,I was trying to commit my self-discovered Yang$_{n}(F)$ number systems, with the below “Yang_n.v” file to the UniMath repository, please find the “.v” file as attached.<Yang_n.v.txt>Thanks in advance and best,-Justin On Nov 15, 2024, at 07:10, Arnoud van der Leer ***@***.***> wrote:﻿
@jscarfy Can you tell a bit about what your intentios is with this PR?

**Comment by arnoudvanderleer** [comment]
Ah, it seems that you added the .v file to your master branch, and only added the updated `files` file on the branch `patch-9`. Can you add the other file(s) to `patch-9` too? Or create a pull request from a different branch?

**Comment by arnoudvanderleer** [comment]
Via a pull request:

1. In your own repository, make sure that all the changes that you want to submit are in the same branch. In this case, most of your changes are on the `master` branch, but the change that you submitted here are in the branch `patch-9`. You can either merge these branches, or (very hacky) download all your files somewhere, create a new branch, and upload the files to that branch.
2. Create a pull request to UniMath from this branch, just like you did for this pull request.

**Comment by jscarfy** [comment]
Do I need to learn additional hacking skills to perform your (very hacky) methods please?  If so do you some of the hacking skills and are willing to teach me/ where else would you recommend me to learn hacking skills please?

Thanks in advance and best,
-Justin

**Comment by jscarfy** [comment]
Thanks and I have my new website up = https://jscarfy.github.io/research.html with lots of new research outputs and more to come

**Comment by jscarfy** [comment]
And also I have my new YouTube channel broadcasting some of my self-discovered mathematics written in my self-invented notations for the rigorous definitions which are used in newly discovered theorems and proofs 

https://youtube.com/@alienmathematicians?si=2AF3afECjLgjdg1x

Best,
-Justin

**Comment by arnoudvanderleer** [comment]
Okay. Can you create a new branch from the master branch in your repository?

**Comment by arnoudvanderleer** [comment]
Okay, can you add this file to this branch? `https://github.com/jscarfy/UniMath/tree/patch-9`

**Comment by arnoudvanderleer** [comment]
Go to https://github.com/jscarfy/UniMath/tree/patch-9
Click "add file".
Upload your file there.

**Comment by jscarfy** [comment]
How do I exact add to this = what do you mean please?jscarfy/UniMath at patch-9github.comThis was under my personal GitHub though I am unsure if I successfully added the “RH.v” file to my own personal GitHub and after everything is on my own personal GitHub I need to commit to the public UniMath repository I think.Could you please walk me through everything step-by-step please.Thanks in advance and best,-Justin On Nov 18, 2024, at 00:24, Pu Justin Yang 楊靐龘 ***@***.***> wrote:﻿what do you mean by that please as I am currently on these pages now:<image0.png><image1.png><image2.png>What do I need to do in which screen above please?Thanks in advance and best,-Justin On Nov 17, 2024, at 23:44, Arnoud van der Leer ***@***.***> wrote:﻿
Okay. Can you create a new branch from the master branch in your repository?

**Comment by arnoudvanderleer** [comment]
Which step do you not understand?

**Comment by jscarfy** [comment]
I have my “Yang_n.v” accidentally saved as a “.txt” file for some reason, would this work (have you tried?) or do you [or rather, GitHub] force me to change it as a [.v] only file please?Justin On Nov 18, 2024, at 00:30, Arnoud van der Leer ***@***.***> wrote:﻿
Which step do you not understand?

**Comment by jscarfy** [comment]
Re: I added them all under the /NumberSystems/ folder as I forgot to create a new separate folder named /NumberTheory/, and I have successfully uploaded all three files of “RH.v”, “Yang_n.v.txt”, and “Yang_n.v” to date- please see attached Thanks in advance and best,-Justin On Nov 18, 2024, at 00:33, Pu Justin Yang 楊靐龘 ***@***.***> wrote:﻿I have my “Yang_n.v” accidentally saved as a “.txt” file for some reason, would this work (have you tried?) or do you [or rather, GitHub] force me to change it as a [.v] only file please?<image0.png>Justin On Nov 18, 2024, at 00:30, Arnoud van der Leer ***@***.***> wrote:﻿
Which step do you not understand?

**Comment by jscarfy** [comment]
Re: what to do now exactly to commit my just uploaded files from my local personal GitHub to the public GitHub please?Thanks in advance and best again.-Justin On Nov 18, 2024, at 00:42, Pu Justin Yang 楊靐龘 ***@***.***> wrote:﻿Re: I added them all under the /NumberSystems/ folder as I forgot to create a new separate folder named /NumberTheory/, and I have successfully uploaded all three files of “RH.v”, “Yang_n.v.txt”, and “Yang_n.v” to date- please see attached <image.png>Thanks in advance and best,-Justin On Nov 18, 2024, at 00:33, Pu Justin Yang 楊靐龘 ***@***.***> wrote:﻿I have my “Yang_n.v” accidentally saved as a “.txt” file for some reason, would this work (have you tried?) or do you [or rather, GitHub] force me to change it as a [.v] only file please?<image0.png>Justin On Nov 18, 2024, at 00:30, Arnoud van der Leer ***@***.***> wrote:﻿
Which step do you not understand?

**Comment by arnoudvanderleer** [comment]
Can you please remove `Yang_n.v.txt`? It is no use here.

**Comment by jscarfy** [comment]
Successfully deleted *On Nov 18, 2024, at 00:48, Arnoud van der Leer ***@***.***> wrote:﻿
Can you please remove Yang_n.v.txt? It is no use here.

**Comment by jscarfy** [comment]
I was wondering the same thing as well…On Nov 18, 2024, at 00:49, Arnoud van der Leer ***@***.***> wrote:﻿
Wait, why is Yang_n.v just one line with
UniMath/NumberSystems/Yang_n.v?

**Comment by jscarfy** [comment]
I upload another version please wait Thanks On Nov 18, 2024, at 00:51, Pu Justin Yang 楊靐龘 ***@***.***> wrote:﻿I was wondering the same thing as well…On Nov 18, 2024, at 00:49, Arnoud van der Leer ***@***.***> wrote:﻿
Wait, why is Yang_n.v just one line with
UniMath/NumberSystems/Yang_n.v?

**Comment by arnoudvanderleer** [comment]
This one is also not good. Can you please make sure that you have the correct file before you upload?

**Comment by jscarfy** [comment]
Uploaded as “Yang_n” only, do I need to change it to “Yang_n.v”, please?

**Comment by arnoudvanderleer** [comment]
Have you looked at the contents of the file that you uploaded?

**Comment by jscarfy** [comment]
YES it contains gibberish and hence I changed the “Yang_n.v” code

**Comment by arnoudvanderleer** [comment]
All right, now we're talking

**Comment by arnoudvanderleer** [comment]
Can you make sure that `RH.v` is also listed in `.package/files`?

**Comment by jscarfy** [comment]
completed!

**Comment by jscarfy** [comment]
And then ?

**Comment by arnoudvanderleer** [comment]
Have you been able to compile / execute these files locally?

**Comment by jscarfy** [comment]
I think no since I keep getting these:

￼

**Comment by arnoudvanderleer** [comment]
Can you tell me a bit more about this problem?

**Comment by jscarfy** [comment]
After I uploaded new files (most likely the “RH.v”) to my local UniMath I keep receiving error messages like the one I sent you.

**Comment by arnoudvanderleer** [comment]
Where do you get these error messages?

**Comment by jscarfy** [comment]
my email inbox ...

**Comment by arnoudvanderleer** [comment]
Okay.
Have you compiled / run these files on your computer?

**Comment by jscarfy** [comment]
in emacs/ coq/ proof general first I assume?

no I have not and how exactly please?

**Comment by arnoudvanderleer** [comment]
If you have not tested this locally, how do you know that the code works? (i.e. is correct?)

**Comment by arnoudvanderleer** [comment]
Currently, it seems that there are errors. For example, the macOS CI indicates that `UniMath.Algebra.All` does not exist.

**Comment by jscarfy** [comment]
I am on a Mac,

I think I have taken a look at this page before and I have ProofGeneral and emacs installed but I am really unsure how exactly to use the combination to date - please send me tutorials - I have seen Prof. Bauer’s videos on this but still havent fully digested…

Justin

**Comment by arnoudvanderleer** [comment]
All right. We have a PR, but it contains code that has not been tested locally. Since it will give a lot of clutter to get out all the bugs online, I am closing this PR. First make sure that you
 - have a local environment;
 - have tested your code in this local environment;
Then file a new PR, and we will take a look at it again.
Until then, please go to the UniMath zulip and ask them there. I (and hopefully a few others) will try to help you get up and running with emacs, proofgeneral and coq

**Comment by jscarfy** [comment]
Oh I think you meant that I need to put everything on both of the public UniMath GitHub under my account and locally on my harddrive copy?Please confirm and thank you On Nov 18, 2024, at 01:36, Arnoud van der Leer ***@***.***> wrote:﻿
Currently, it seems that there are errors. For example, the macOS CI indicates that UniMath.Algebra.All does not exist.

**Comment by jscarfy** [comment]
Thanks for the below and best,Justin On Nov 18, 2024, at 01:43, Arnoud van der Leer ***@***.***> wrote:﻿
All right. We have a PR, but it contains code that has not been tested locally. Since it will give a lot of clutter to get out all the bugs online, I am closing this PR. First make sure that you

have a local environment;
have tested your code in this local environment;

Then file a new PR, and we will take a look at it again.
Until then, please go to the UniMath zulip and ask them there. I (and hopefully a few others) will try to help you get up and running with emacs, proofgeneral and coq

**Comment by arnoudvanderleer** [comment]
> Oh I think you meant that I need to put everything on both of the public UniMath GitHub under my account and locally on my harddrive copy? Please confirm and thank you.

Yes, you will need to have everything both at https://github.com/jscarfy/UniMath and on your local computer. You first test your code locally, and then upload it to github. That way, we make sure that everything that ends up in a pull request, has already been tested, so it only needs a few tweaks.

**Pull request closed without merging**
