### PR TITLE
Remove the CI run for 8.20, since coq latest is now at 8.20

### LINKED ISSUE #1934: Adapt the CI
Coq 8.20 is out: https://coq.discourse.group/t/coq-8-20-0-is-out/2425, so the latest version of Coq is 8.20 now. This means that the CI is testing for Coq 8.20 twice, which is unnecessary.

### PR DESCRIPTION
**Pull request by arnoudvanderleer**
Resolves #1934

### CODE REVIEW

**Review by nmvdw — APPROVED** [review]

**Comment by rmatthes** [comment]
Which version of Coq is now being used for latest - is it really 8.20 or still its release candidate? But in both cases, the current CI setting will have a duplicate entry.

**Comment by nmvdw** [comment]
> Which version of Coq is now being used for latest - is it really 8.20 or still its release candidate? But in both cases, the current CI setting will have a duplicate entry.

Coq 8.20 is the latest version now. It came out today.

**Comment by arnoudvanderleer** [comment]
@rmatthes Note that every CI run prints the versions that it runs:
```
Print versions
  + (script @ line 9) $ opam --version
  2.2.1
  + (script @ line 10) $ opam exec -- dune --version
  3.13.1
  + (script @ line 11) $ opam exec -- coqc --version
  The Coq Proof Assistant, version 8.20.0
  compiled with OCaml 4.13.1
  + (script @ line 12) $ endGroup
```

**Comment by rmatthes** [comment]
Thank you. Yesterday, I heard that the images for CI were not yet available. But they seem to be now.

**Comment by arnoudvanderleer** [comment]
It was useful to have 8.20 explicitly because coq dev was at 8.21 while latest was still at 8.19 (see #1896 )
It is of course conceivable that this will not be the last time that there is a gap between dev and latest, but for now we are fine.

**Pull request merged**
