### PR TITLE
Temporarily remove GrpdHITs-dev from CI.

### PR DESCRIPTION
**Pull request by m-lindgren**
See #1693.

### CODE REVIEW

**Review by nmvdw — APPROVED** [review]

**Comment by peterlefanulumsdaine** [comment]
lgtm!

**Comment by benediktahrens** [comment]
Are there any plans to fix GrpdHITs? How can we avoid forgetting GrpdHITs after deactivating it in CI?

**Comment by m-lindgren** [comment]
> How can we avoid forgetting GrpdHITs after deactivating it in CI?

By next release of Coq the GrpdHITs-latest build will fail as well so that'll remind us to either fix it or remove GrpdHITs from the CI completely (or only build GrpdHITs with 8.17).

**Comment by nmvdw** [comment]
There are plans to fix it. However, the precise fix depends on the features in the new version of Coq. Currently, one implements HITs using private inductive types, and a nicer way would be to add rewrite rules. This is not possible at the moment, but some people are actually working on adding that feature (if I heard correctly, they have an open PR). If rewrite rules are added, then the fix might be different compared to if they are not added. In addition, the CI will indeed remind us when we switch to a new version of Coq. 

I would like to keep GrpdHITs actively maintained and in the CI.

**Pull request merged**
