### PR TITLE
uniform use of underscores

### PR DESCRIPTION
**Pull request by DanGrayson**
see https://github.com/UniMath/UniMath/issues/687#issuecomment-485281491

### CODE REVIEW

**Comment by siddharthist** [comment]
What do we think about changing some existing identifiers to match? I'm working on a parser for (some subset of) the Coq grammar that should allow us to do some batch renaming if we're interested.

**Comment by DanGrayson** [comment]
Emacs'  tag facility makes replacement easy:
```
M-R runs the command tags-query-replace (found in global-map), which is an
interactive autoloaded compiled Lisp function in ‘etags.el’.

It is bound to M-R, <menu-bar> <edit> <replace> <tags-repl>.

(tags-query-replace FROM TO &optional DELIMITED FILE-LIST-FORM)

Do ‘query-replace-regexp’ of FROM with TO on all files listed in tags table.
Third arg DELIMITED (prefix arg) means replace only word-delimited matches.
If you exit (M-x keyboard-quit, RET or q), you can resume the query replace
with the command M-,.
Fourth arg FILE-LIST-FORM non-nil means initialize the replacement loop.

If FILE-LIST-FORM is non-nil, it is a form to evaluate to
produce the list of files to search.
```

Anything in `Foundations` should be left to me.

**Comment by siddharthist** [comment]
@DanGrayson Let's make an issue after this PR is merged to consider changing names in Foundations to be consistent with this schema. 

It's amazing what Emacs can do!

**Comment by DanGrayson** [comment]
That might be premature, since there are other things to consider when choosing a name, such as capitalization.

**Pull request merged**
