### PR TITLE
empty arity sent to constant sig instead of identity sig

### PR DESCRIPTION
**Pull request by amblafont**

### CODE REVIEW

**Comment by rmatthes** [comment]
Why is the PR closed?

**Comment by rmatthes** [comment]
LGTM

**Comment by DanGrayson** [comment]
Reopening.  Probably the closing was due the to temporary deletion of the branch.  Maybe `git --force` operates that way, behind the scenes.

**Comment by DanGrayson** [comment]
Indeed, at https://help.github.com/articles/about-pull-requests/ they say not to use forced push on a pull request branch, for it will corrupt the pull request.

**Pull request merged**
