### PR TITLE
Primitive projections

### LINKED ISSUE #111: total2 as record, use of "primitive projections" ?
As far as I recall, total2 was, at some point, defined as a record type. At the moment, it is defined as an inductive type. (The comments in uuu.v still say that a record type is used.)
What was the reason for changing from record to an ordinary inductive? 

If we switched back to total2 being defined as a record type, we could use the "Set Primitive Projections" option which, as @JasonGross told me, would provide significant speedup of compilation (at least it did for HoTT/HoTT).
It would also provide eta for dependent pairs, which might or might not be something we want.

### LINKED ISSUE #643: switch total2 to Record to make "apply" totally cool
Here is the documentation of the tactic "apply":

"apply term

This tactic applies to any goal. The argument term is a term well-formed in the local context. The
tactic apply tries to match the current goal against the conclusion of the type of term. If it succeeds,
then the tactic returns as many subgoals as the number of non-dependent premises of the type of term.
If the conclusion of the type of term does not match the goal and the conclusion is an inductive type
isomorphic to a tuple type, then each component of the tuple is recursively matched to the goal in the
left-to-right order."

The last sentence would be totally cool for us if only total2 were isomorphic to a tuple type, because then, if we needed some sequence of projections `pr1` and `pr2` applied to a term `w` to fulfill the current goal, then we could just use `apply w` instead of something like `apply (pr1 (pr2 (pr1 (pr2 (pr1 w)))))`.  It would be if only `total2` were defined as a record instead of as an inductive type.  I have tested it, and that change would work for us.  All we have to do is to change the definition of `total2` and to delete the definitions of `pr1` and of `pr2`.

We have to switch `total2` to be a record soon, anyway, once we get primitive projections working, so we can have the benefit of eta-reduction for pairs.  I propose we do it now, so we can get the benefit of this cool feature of `apply`.

Yes, I know Foundations is "locked", but this is such a simple change, which we have to implement eventually anyway, that it should be possible to consider it and approve it in one minute.

### PR DESCRIPTION
**Pull request by DanGrayson**
I finally got primitive projections with η-reduction for pairs working completely.  I ran a time trial and observed a speed-up of 56%.  That will go a long way to postponing the day when UniMath fissions or we start paying for longer travis builds.

Now, to get C^op^op and C to be judgmentally the same, all we need to do is to have two associativity axioms, f(gh)=(fg)h and (fg)h=f(gh), so the construction of C^op can just interchange them instead of applying pathsinv0.

The only file in the Foundations that is affected is Preamble.v, where total2 is defined. I added my defense of the use of the "match" construction for this one thing, stated in the comment https://github.com/UniMath/UniMath/pull/647#issuecomment-286489637 , to a comment in the file Preamble.v, for future reference

This includes #647.  
This resolves #643.  
This would help with #602.  
This resolves #111.
This affects #77.

### CODE REVIEW

**Comment by DanGrayson** [comment]
The comment https://github.com/UniMath/UniMath/pull/647#issuecomment-286529751 presumably applies here, even though it doesn't apply there.

**Comment by DanGrayson** [comment]
I noticed your comment on the google group : 

" the only published Martin-Lof type theory with the eta for products is MLTT79. So UniMath is MLTT79 minus the reflection rule for the equality and plus the resizing rule(s)"

your comment in https://github.com/UniMath/UniMath/pull/647#issuecomment-286441593 is not valid : 

" By doing this change we move the UniMath another step away from the Martin-Lof type theory "

So now I wonder whether the phrase "Martin-Lof type theory" has a definite meaning, with regard to eta reduction.

In any case, perhaps it is time for UniMath-2.0, as you suggest in https://github.com/UniMath/UniMath/pull/647#issuecomment-286441593

**Comment by vladimirias** [comment]
My comment on the google group is about dependent products not dependent sums.

**Comment by DanGrayson** [comment]
Re: "My comment on the google group is about dependent products not dependent sums."

Oh, I misunderstood, thank you for the correction.

**Comment by mortberg** [comment]
So this PR gives us eta for dependent sums and a 56% speedup? That is pretty impressive.

If this is merged I think formalizing mathematics in UniMath will be even more pleasant. The lack of eta for pairs is sometimes annoying me, but the slowness has been really bothering me lately (every time I make some change early on I have to wait for about 1.5 hours on my laptop to compile the entire library, luckily I don't have to do this too often).

**Comment by vladimirias** [comment]
I agree. Should we start UniMath-2.0 then?

**Comment by DanGrayson** [comment]
```
The 10 slowest files:

without records and primitive projections:

    user time 321.70: UniMath/HomologicalAlgebra/TranslationFunctors
    user time 257.96: UniMath/HomologicalAlgebra/MappingCone
    user time 251.80: UniMath/HomologicalAlgebra/KAPreTriangulated
    user time 209.78: UniMath/SubstitutionSystems/LiftingInitial_alt
    user time 190.03: UniMath/HomologicalAlgebra/MappingCylinder
    user time 189.73: UniMath/HomologicalAlgebra/KA
    user time 171.84: UniMath/HomologicalAlgebra/CohomologyComplex
    user time 163.66: UniMath/SubstitutionSystems/MonadsFromSubstitutionSystems
    user time 162.91: UniMath/HomologicalAlgebra/KATriangulated
    user time 138.55: UniMath/SubstitutionSystems/LiftingInitial

with:

    user time 174.42: UniMath/HomologicalAlgebra/TranslationFunctors
    user time 141.92: UniMath/CategoryTheory/limits/graphs/pushouts
    user time 126.28: UniMath/HomologicalAlgebra/MappingCone
    user time 112.85: UniMath/CategoryTheory/limits/graphs/pullbacks
    user time 111.56: UniMath/HomologicalAlgebra/KAPreTriangulated
    user time 101.27: UniMath/HomologicalAlgebra/KA
    user time 80.00: UniMath/HomologicalAlgebra/KATriangulated
    user time 70.32: UniMath/CategoryTheory/LocalizingClass
    user time 64.85: UniMath/HomologicalAlgebra/CohomologyComplex
    user time 49.99: UniMath/CategoryTheory/limits/graphs/equalizers
```

**Comment by DanGrayson** [comment]
Starting UniMath-2.0 sounds like a great idea!

**Comment by vladimirias** [comment]
Thank you for the timing info, but the first and the second list in your timing message are different.

**Comment by DanGrayson** [comment]
Yes, the 10 slowest files from the first run are different from the 10 slowest files of the second run.

**Comment by mortberg** [comment]
Interesting that pushouts and pullbacks got slower. I can definitely spend some time making them faster once this is merged.

**Comment by DanGrayson** [comment]
```
The 10 slowest files before this PR, without records and primitive projections:

    user time 321.70: UniMath/HomologicalAlgebra/TranslationFunctors
    user time 257.96: UniMath/HomologicalAlgebra/MappingCone
    user time 251.80: UniMath/HomologicalAlgebra/KAPreTriangulated
    user time 209.78: UniMath/SubstitutionSystems/LiftingInitial_alt
    user time 190.03: UniMath/HomologicalAlgebra/MappingCylinder
    user time 189.73: UniMath/HomologicalAlgebra/KA
    user time 171.84: UniMath/HomologicalAlgebra/CohomologyComplex
    user time 163.66: UniMath/SubstitutionSystems/MonadsFromSubstitutionSystems
    user time 162.91: UniMath/HomologicalAlgebra/KATriangulated
    user time 138.55: UniMath/SubstitutionSystems/LiftingInitial

The same files, with:

    user time 174.42: UniMath/HomologicalAlgebra/TranslationFunctors
    user time 126.28: UniMath/HomologicalAlgebra/MappingCone
    user time 111.56: UniMath/HomologicalAlgebra/KAPreTriangulated
    user time  21.08: UniMath/SubstitutionSystems/LiftingInitial_alt
    user time  17.48: UniMath/HomologicalAlgebra/MappingCylinder
    user time 101.27: UniMath/HomologicalAlgebra/KA
    user time  64.85: UniMath/HomologicalAlgebra/CohomologyComplex
    user time  12.07: UniMath/SubstitutionSystems/MonadsFromSubstitutionSystems
    user time  80.00: UniMath/HomologicalAlgebra/KATriangulated
    user time  16.23: UniMath/SubstitutionSystems/LiftingInitial
```

**Comment by mortberg** [comment]
Wow, incredible that LiftingInitial and LiftingInitial_alt got that much faster! I spent half a day trying to speed them up by hand, leading only to a few seconds speedup in total...

**Comment by DanGrayson** [comment]
Now I wonder whether Coq was the same Coq in the two runs.  Perhaps I should repeat the timing trials, after adding something to the makefile to display the current sub/coq commit.

**Comment by vladimirias** [comment]
Yes, this looks good.

**Comment by mortberg** [comment]
About UniMath 2.0: This system will be UniMath 1.0 with eta for pairs? (With total2 defined as a Record in the implementation)  So it is MLTT79 without equality reflection and W-types, but with eta for pairs, the univalence axiom and resizing rules?

**Comment by DanGrayson** [comment]
Re: " I have to wait for about 1.5 hours on my laptop to compile the entire library"

Anders, I wonder whether something like "make -j2" or "make -j4" would speed it up for you.  (if you have  multiple cores).

**Comment by DanGrayson** [comment]
Okay, I just ran time trials again on my branch and on the master branch, with the latest Coq v8.6 on both, and got an improvement from 58m20.226s to 26m16.951s for user time, and from 35m9.172s to 18m13.682s for real time (elapsed time).

**Comment by DanGrayson** [comment]
@benediktahrens , if this is okay with you, it seems we can merge.  It's okay with Vladimir, provided we maintain the code just before the merge on its own branch, UniMath-1.0, so there will be something concrete still in existence for demonstration purposes for papers that don't include eta for pairs.  I'll take care of setting that up afterward and make an issue for it now.

I think I'll set it up so the two branches have the exact same Makefile, by putting the list of packages in a separate file.  Both branches will track the latest Coq releases.

**Comment by benediktahrens** [comment]
Why does this PR change the Coq version, and what version does it change to?

**Comment by DanGrayson** [comment]
I thought it might as well change the coq version to the latest v8.6.

**Comment by benediktahrens** [comment]
On 03/15/2017 07:21 PM, Daniel R. Grayson wrote:
> I thought it might as well change the coq version to the latest v8.6.

I thought we had agreed on going with the latest released version?

**Comment by benediktahrens** [comment]
On 03/15/2017 07:04 PM, Daniel R. Grayson wrote:
> Both branches will track the latest Coq releases.

https://github.com/coq/coq/releases ?

**Comment by benediktahrens** [comment]
lgtm except for change of coq

**Comment by DanGrayson** [comment]
Yes.  Is that one not released?

**Comment by benediktahrens** [comment]
On 03/15/2017 08:54 PM, Daniel R. Grayson wrote:
> Yes.  Is that one not released?

I would call 'released' what appears on

[1] https://github.com/coq/coq/releases

and on

[2] https://coq.inria.fr/download

The latest release on [1] is the tag V8.6, which points to 0d14388 ,
which is also the commit currently referred to in our submodule setting.

Maybe we can wait for V8.6pl1 ?


The reason for sticking with released (in the sense above) versions was
to allow others to compile UniMath with a precompiled Coq.
This might fail if we don't test against the latest released Coq.

**Comment by DanGrayson** [comment]
Okay, I've fixed it so sub/coq is unchanged.

**Comment by benediktahrens** [comment]
On 03/15/2017 09:51 PM, Daniel R. Grayson wrote:
> I've made a branch called "UniMath-1.0", see https://github.com/UniMath/UniMath/tree/UniMath-1.0, based on the current "master" -- anticipating this PR will be the next one pulled.
> 
> If we want a branch called "UniMath-2.0", should we rename "master" to that?
> 

I think we should keep the name "master", which should be the branch
against which PRs are filed.

A branch "UniMath-2.0" should be made once we want a version that
diverges from master.

**Comment by DanGrayson** [comment]
Shall we activate travis on the new branch?  Shall we have pull requests, or should I just
maintain it silently?

**Comment by DanGrayson** [comment]
Okay, I'll just take care of it silently.

**Comment by DanGrayson** [comment]
Re: "Is there an option to (de)activate Travis on a per-branch basis? I was
not aware of that."

Well, I know almost nothing about it.  Maybe any pull request to any branch would activate it.

**Comment by benediktahrens** [comment]
On 03/15/2017 10:17 PM, Daniel R. Grayson wrote:
> Re: "Is there an option to (de)activate Travis on a per-branch basis? I was
> not aware of that."
> 
> Well, I know almost nothing about it.  Maybe any pull request to any branch would activate it.  


One can black- and white-list branches:

https://docs.travis-ci.com/user/customizing-the-build/
"Building specific branches"

One can also have different travis.yml files on different branches.

**Pull request merged**
