### PR TITLE
Clean limits

### PR DESCRIPTION
**Pull request by mortberg**
This is based on https://github.com/UniMath/UniMath/pull/835 so please merge that first.

This PR fixes:
- Remove the prefix (Co)Cone from particular limits ((Bin)(Co)products, etc.) in order to make naming of lemmas and definitions more consistent.
- Add some implicit arguments.
- Use more unicode

### CODE REVIEW

**Comment by peterlefanulumsdaine** [comment]
Looks great to me!

**Comment by DanGrayson** [comment]
lgtm

**Comment by DanGrayson** [comment]
Ideally, a PR based on another would not be submitted until the other has been pulled, so the diffs will be relevant.

**Comment by benediktahrens** [comment]
lgtm, to be merged after #835

**Pull request merged**
