### PR TITLE
Cleaned NaturalNumbers.v

### PR DESCRIPTION
**Pull request by tpannila**
Cleaned long lines in NaturalNumbers.v and added Contents comment.

### CODE REVIEW

**Comment by benediktahrens** [comment]
Starting from `natgehandminuslinv`, the proof code is not indented any more. Before that, you had used the convention of indenting proof code by 2 spaces.

Starting from `isplushrelnatgth`, some proofs have remained in one line, with `Proof.` and `Defined.` in the same line.

**Comment by benediktahrens** [comment]
lgtm modulo the small incompletenesses mentioned above

**Comment by tpannila** [comment]
@benediktahrens , there is a block of code in a comment starting at `natgehandminuslinv` .
The block also contains an unfinished definition `natlehandminusr` and a proof without 
statement. Thus I left the comment untouched.  Should I treat code inside a comment the
same as code outside a comment?

**Comment by benediktahrens** [comment]
On 09/07/2016 12:23 AM, Tomi Pannila wrote:
> @benediktahrens , there is a block of code in a comment starting at `natgehandminuslinv` .
> The block also contains an unfinished definition `natlehandminusr` and a proof without 
> statement. Thus I left the comment untouched.  Should I treat code inside a comment the
> same as code outside a comment?

Sorry, I only looked at the diff and hence did not see the context.
No, don't work on commented code, that is likely to be a wasted effort.

**Comment by vladimirias** [comment]
It is possible that there will be a major reworking of the part of hnat that concerns minus.

Vladimir.

**Comment by vladimirias** [comment]
LGTM and merging.

**Pull request merged**
