### PR TITLE
Renaming

### PR DESCRIPTION
**Pull request by DanGrayson**
These cosmetic changes were originally part of #257.

### CODE REVIEW

**Comment by benediktahrens** [comment]
This PR will conflict with #422 .

It would be great if everybody helped reviewing and merging PRs in addition to (and before, possibly) filing their own, in particular when the to-be-filed PR touches many files.

**Comment by DanGrayson** [comment]
I'd be happy to do that if my PR from December weren't still in limbo.

**Comment by benediktahrens** [comment]
I don't understand what this PR has to do with your old PR #257 from December, other than that it implements some similar changes.
The renaming done for this PR would have been just as easy *after* merging #422 as *before*, since this PR does not make use of any work done for #257.

In general, before doing a mass renaming or similar automatized modification of a large amount of code, it would be good to have outstanding PRs merged.

**Comment by benediktahrens** [comment]
On 09/04/2016 03:56 PM, Daniel R. Grayson wrote:
> I'd be happy to do that if my PR from December weren't still in
> limbo.

Maybe we should add a rule on separation of concerns for PRs into our
README. Every PR should address exactly one issue.
(Addition of code counts as one issue.)

https://en.wikipedia.org/wiki/Separation_of_concerns

**Comment by DanGrayson** [comment]
Re: "I don't understand what this PR has to do with your old PR #257 from December, other than that it implements some similar changes."

They're unrelated.  It's just that with my PR not in limbo I would be less discouraged.

**Comment by DanGrayson** [comment]
Re: "Maybe we should add a rule on separation of concerns for PRs into our README. Every PR should address exactly one issue. (Addition of code counts as one issue.)"

It's a good idea.  (But it can be added it to UniMath/README.md.)

**Comment by vladimirias** [comment]
This would be good but I am not sure to what extent it is possible. If you move upstream some code from a file this code may land up in many different places. Would this still be allowed as a single PR?

**Comment by benediktahrens** [comment]
On 09/04/2016 05:09 PM, Vladimir Voevodsky wrote:
> This would be good but I am not sure to what extent it is possible. 
> If you move upstream some code from a file this code may land up in 
> many different places. Would this still be allowed as a single PR?

I'd suggest that people do such upstream moves into one package at a
time only, but not necessarily into only one file.

**Comment by vladimirias** [comment]
What do you call “one package”?

**Comment by benediktahrens** [comment]
On 09/04/2016 05:53 PM, Vladimir Voevodsky wrote:
> What do you call “one package”?

In our READMEs, we call the subdirectories of UniMath/UniMath "packages".

Hence, Foundations is a package, as is CategoryTheory, Ktheory, and so on.

**Comment by DanGrayson** [comment]
There are too many conflicts now, closing.

**Pull request closed without merging**
