### PR TITLE
Cleaned Rigs_and_Rings.v

### PR DESCRIPTION
**Pull request by tpannila**
Cleaned long lines in Rigs_and_Rings.v and added Contents comment.

### CODE REVIEW

**Comment by benediktahrens** [comment]
lgtm

**Comment by vladimirias** [comment]
Why is there Travis build in progress?

**Comment by benediktahrens** [comment]
On 09/05/2016 09:18 PM, Vladimir Voevodsky wrote:
> Why is there Travis build in progress? 

I see the same, and don't know why.
However, if you click on "Details", it'll lead you to [1], where you see
that the build succeeded.
To be safe, I have also checked that the PR builds on my machine.

[1] https://travis-ci.org/UniMath/UniMath/builds/151260869

**Comment by DanGrayson** [comment]
Every time a pull request is accepted, all pending pull requests have to be retested.  I merged #424 14 minutes ago.

**Comment by benediktahrens** [comment]
On 09/05/2016 09:22 PM, Daniel R. Grayson wrote:
> Every time a pull request is accepted, all pending pull requests have
> to be retested.  I merged #424 14 minutes ago.

I don't think that this is indeed happening (even though it maybe should).
You can look at the time when the outstanding PRs were tested. Some
tests ran many days ago.

**Comment by DanGrayson** [comment]
Yes, you must be right.

But when did the build complete?  I see no date information associated with it.  If there is no way to tell the date, lets add a line "date" to the top of the test script.

**Comment by benediktahrens** [comment]
On 09/05/2016 09:32 PM, Daniel R. Grayson wrote:
> Yes, you must be right.
> 
> But when did the build complete?  I see no date information
> associated with it.  If there is no way to tell the date, lets add a
> line "date" to the top of the test script.

If you click on "Details", you'll land on the Travis website.
There, you will see "24 days ago", and if you hover over the calendar
symbol, it'll give you a precise timestamp.
No need to modify the test script.

**Comment by DanGrayson** [comment]
So the indication that a check is pending is completely bogus.

**Comment by benediktahrens** [comment]
On 09/05/2016 09:39 PM, Daniel R. Grayson wrote:
> So the indication that a check is pending is completely bogus.

Yes, it looks like it.

**Comment by vladimirias** [comment]
I think we should ask Tomi to do the same with this PR that he did with the Monoids_and_Groups one.

**Comment by tpannila** [comment]
@vladimirias , I do the same coding style fix for #423 , #425 (this PR), #426 and #427 .

**Comment by vladimirias** [comment]
Great!

**Comment by vladimirias** [comment]
Please change (* End of the file algebra1c.v *) to (* End of file *). Otherwise LGTM.

**Comment by tpannila** [comment]
@vladimirias , I fixed coding style in #423 , #425 , #426 , and #427

**Comment by vladimirias** [comment]
Can we merge this PR?

**Comment by DanGrayson** [comment]
Fine with me, I'll do it.

**Pull request merged**
