### PR TITLE
call sanity checks in CI in a way that makes error appear last

### PR DESCRIPTION
**Pull request by benediktahrens**
see #1611

### CODE REVIEW

**Comment by DanGrayson** [comment]
There may be multiple errors.  This will move only the first error into prominence.

**Comment by benediktahrens** [comment]
> There may be multiple errors. This will move only the first error into prominence.

For me, this would be an improvement over the current situation. A better, but also more complicated, mechanism could save the errors in an intermediate file and print that file at the end.

**Comment by DanGrayson** [comment]
I think it's pretty easy to search the output for the string " *** ", thereby finding all the errors.

**Comment by m-lindgren** [comment]
Maybe a solution would be to grep the output for '***' if there is an error? If we also implement what Peter suggested in #1567 the output should be pretty informative.

**Comment by peterlefanulumsdaine** [comment]
Is there any reason not to merge this?  I agree with @benediktahrens that it’s an incremental improvement on the current situation.  The suggested further improvements could be great, but it’s been 3 months without progress on them, so I suggest merging this for now, and noting this discussion in #1567 (or another issue) for possible future improvements.

**Review by m-lindgren — APPROVED** [review]

**Pull request merged**
