### PR TITLE
Lemmas for proving equality of sequences

### PR DESCRIPTION
**Pull request by vladimirias**
I have added two lemmas that allow to prove (transportational) equality of
 sequences whose lengths are not definitionally equal. In particular, these lemmas can be used in
the proofs of such results as associativity of concatenation of sequences and the right unity
axiom for the empty sequence.

### CODE REVIEW

**Comment by benediktahrens** [comment]
We have the following rule:
"
Always use Coq's proof structuring syntax ( { } + - * ) to focus on a single goal immediately after a tactic creates additional goals.
"
For this PR, the following would be nice:
```
assert (foo : bar).
{ ... < construct foo > ... }
< continue main proof >
```

**Comment by vladimirias** [comment]
Yes, sorry. I have not quite learned this structuring syntax :). I'll fix it.

**Comment by tpannila** [comment]
This PR looks good to me. I was able to complete the proofs of `concatenate_0` and
`concatenateStep` by using `seq_key_eq_lemma` and by replacing the invmap in the definition of
concatenate by a more computational one. I will file a pull request of these after this pull
requests has been merged. 

At first, when I played with this pull request, I was able to find a bug(?) in Coq. 

```
Definition concatenate_0 {X} (s:Sequence X) (t:stn 0 -> X) : concatenate s (0,,t) = s.
Proof.
  intros.
  induction s as [n s].
  simple refine (total2_paths2 _ _).
  { simpl. apply natplusr0. }
  { simpl. rewrite transportf_fun. apply funextsec. intros i.
    induction (coprod_rect (λ _ : stn n ⨿ stn 0, X) (λ j : stn n, s j) (λ k : stn 0, t k)).
```

The last induction gives the following error `Anomaly: Not an evar resulting of a dependent
binding. Please report.` . Note that I have not checked if this happends with 8.5pl3.

**Comment by benediktahrens** [comment]
On 10/29/2016 12:32 PM, Tomi Pannila wrote:
> 
> At first, when I played with this pull request, I was able to find a bug(?) in Coq. 
> 
> ```
> Definition concatenate_0 {X} (s:Sequence X) (t:stn 0 -> X) : concatenate s (0,,t) = s.
> Proof.
>   intros.
>   induction s as [n s].
>   simple refine (total2_paths2 _ _).
>   { simpl. apply natplusr0. }
>   { simpl. rewrite transportf_fun. apply funextsec. intros i.
>     induction (coprod_rect (λ _ : stn n ⨿ stn 0, X) (λ j : stn n, s j) (λ k : stn 0, t k)).
> ```
> 
> The last induction gives the following error `Anomaly: Not an evar resulting of a dependent
> binding. Please report.` . Note that I have not checked if this happends with 8.5pl3.

The very same error occurs with 8.5pl3.

**Pull request merged**
