### PR TITLE
improve travis test script

### LINKED ISSUE #465: Cloning lablgtk frequently fails on Travis
We clone lablgtk every time, even when we don't compile CoqIDE.
Is there a way to not do that?

### PR DESCRIPTION
**Pull request by DanGrayson**
... so it doesn't check out the submodules in every build

This will resolve #465

### CODE REVIEW

**Comment by benediktahrens** [comment]
Perfect, thanks!

**Comment by DanGrayson** [comment]
Step 1 completed and lablgtk was not downloaded.  So it works.

**Comment by benediktahrens** [comment]
On 09/21/2016 04:05 PM, Daniel R. Grayson wrote:
> Step 1 completed and lablgtk was not downloaded.  So it works.

Right. And lablgtk is cloned "at the right moment" here:
https://travis-ci.org/UniMath/UniMath/jobs/161632665#L830

**Comment by benediktahrens** [comment]
Note that the recursive cloning takes a significant amount of time, see, e.g., here:
https://travis-ci.org/UniMath/UniMath/jobs/161527555#L105  - 134seconds. 
Good thing we now only fetch what we need.

**Pull request merged**
