### PR TITLE
Move all documentation to the `/documentation` folder and do a first organization of the files

### PR DESCRIPTION
**Pull request by arnoudvanderleer**
Adding this as a draft, to notify y'all that I am working on this. If you have any input, let me know.
The intention is that this will bring the documentation up to date and make it somewhat coherent, addresing issues like #1860, #1931, #1929, #1587, #1360, #1400,

### CODE REVIEW

**Comment by benediktahrens** [comment]
This is a great effort, thanks for taking care of this.
Moving files and modifying them in one go makes things harder to track (at least for me). Would it be a good idea to merge this PR soon and then do further updates to the documentation?

**Comment by arnoudvanderleer** [comment]
Hm, we could do that, although currently almost every link in the documentation is broken. Is this still your preference?

**Comment by benediktahrens** [comment]
Ah, right, maybe not! But any deeper change could be postponed, such as updating installation instructions.

**Comment by arnoudvanderleer** [comment]
All right, fair

**Comment by arnoudvanderleer** [comment]
@benediktahrens Would it be an idea to merge this, and then continue working on the contents of the files in a new PR?

**Pull request merged**
