### PR TITLE
work around a bug in Coq 8.9.0 under Mac OS X

### PR DESCRIPTION
**Pull request by DanGrayson**
... by not building "coqchk", which we don't use anyway

### CODE REVIEW

**Comment by benediktahrens** [comment]
Is there a bug report about that already?

**Comment by DanGrayson** [comment]
> Is there a bug report about that already?

I can't find one.

**Comment by DanGrayson** [comment]
Why doesn't travis ever get started checking this pull request?  I've restarted it 5 times.

**Comment by DanGrayson** [comment]
Travis not starting is a known travis bug: https://github.com/travis-ci/travis-ci/issues/10179

**Comment by DanGrayson** [comment]
The fix to Coq was made here : https://github.com/coq/coq/commit/3e431c753c13eb81423943be64b640284526ad3b

**Pull request merged**
