### PR TITLE
clean up Foundations, part 2

### PR DESCRIPTION
**Pull request by DanGrayson**
implement some of the changes suggested in #763

### CODE REVIEW

**Comment by benediktahrens** [comment]
@DanGrayson : Your PR changes to Coq8.7, hence the Travis failure. Could you revert the change to sub/coq?

**Comment by DanGrayson** [comment]
Oops, good catch.

**Comment by rmatthes** [comment]
lgtm

**Comment by benediktahrens** [comment]
lgtm

**Pull request merged**
