### PR TITLE
Pushout for displayed categories

### PR DESCRIPTION
**Pull request by EwenBC**
Screenshot_2023-06-06_10-43-44
Creation of the pushout for displayed categories. Given a displayed category D over  C and a functor F from C to  C', creation of a category D' over C' and a displayed functor DF over F. The following universal property is verified : 
For all D'' displayed category over C'', H functor from C' to C'' and DG displayed functor from D' to D'' over F · H,
we have a unique DH over H such that DG = DF·DH. (picture above)

### CODE REVIEW

**Comment by rmatthes** [comment]
I am missing a description. What is a "pushfoward" meant to be?

**Comment by EwenBC** [comment]
> I am missing a description. What is a "pushfoward" meant to be?
I've made some edits, is is better ?

**Comment by rmatthes** [comment]
A nice diagram that is now only in the GitHub repo. No answer to my question. What does the name of the file mean? I assume there is a typo in it.

**Comment by DanGrayson** [comment]
Yes, Pushfoward.v certainly has a typo in it.

**Pull request merged**
