### PR TITLE
make assert into separate lemma

### PR DESCRIPTION
**Pull request by Tobias-Schmude**
The proof of cartesian_factorisation_unique in CategoryTheory/DisplayedCats/Fibrations.v asserts something that might reasonably be a separate lemma.

### CODE REVIEW

**Comment by benediktahrens** [comment]
@Tobias-Schmude : shouldn't the goal `goal'` be removed, then?

**Review by benediktahrens — CHANGES_REQUESTED** [review]
Subgoal needs to be removed

**Comment by Tobias-Schmude** [comment]
I removed the assertion. Should I click on "re-request review" now?

**Comment by benediktahrens** [comment]
Sure, that sounds fun!

**Pull request merged**
