### PR TITLE
Declare hint databases in the prelude

### PR DESCRIPTION
**Pull request by ppedrot**
Adapt to coq/coq#8984.

### CODE REVIEW

**Comment by benediktahrens** [comment]
@ppedrot : Thanks a lot for the PR. Is it important for us to understand what these commands do?
I assume that this is something that is part of the Coq Prelude that we do not load (-noinit)?

**Comment by ejgallego** [comment]
> I assume that this is something that is part of the Coq Prelude that we do not load (-noinit)?

They were loaded by ML code, they just declare some empty databases that rewrite needs to work; they shouldn't affect the logic.

**Comment by ppedrot** [comment]
Indeed. Before, these hint bases used to be created by the OCaml files.

**Comment by benediktahrens** [comment]
On 02/04/2019 17:55, Pierre-Marie Pédrot wrote:
> Indeed. Before, these hint bases used to be created by the OCaml files.

Thanks a lot to you and the Coq developers in general for taking care of 
this, and for keeping UniMath compatible with Coq in general!

**Pull request merged**
