### PR TITLE
Refactoring enriched categories, work on Kleisli categories

### PR DESCRIPTION
**Pull request by nmvdw**
This PR builds forth upon https://github.com/UniMath/UniMath/pull/1797.

This PR is a bit big. It contains three refactorings:
- To prove that a transformation is enriched, `nat_trans_enrichment_via_comp` is chosen, because this simplifies the proofs. 
- The composition operator in the Kleisli category and Eilenberg-Moore category is slightly changed. Now `precomp_arr` and `postcomp_arr` are used systematically, because this simplifies the proofs. This can especially be noted in the file on Kleisli categories. Material is added about the universal property of the non-univalent Kleisli category, but the file became significantly smaller.
- I finally proved that an enriched transformation is invertible if and only if its underlying transformation is invertible. Before, I didn't use `nat_trans_enrichment_via_comp` and that made the proof harder. Now the proof is rather simple.

I also added the functors and transformations for the universal property of the non-univalent Kleisli category.

### CODE REVIEW

**Comment by benediktahrens** [comment]
o_O, a merge conflict...

**Comment by nmvdw** [comment]
> o_O, a merge conflict...

solved

**Comment by benediktahrens** [comment]
@nmvdw : you mention that the files get smaller, but just to be sure that no errors are creeping in (such as files forgotten to commit) - the PR decreases the line count by 4000. Is that intended?

**Comment by nmvdw** [comment]
> @nmvdw : you mention that the files get smaller, but just to be sure that no errors are creeping in (such as files forgotten to commit) - the PR decreases the line count by 4000. Is that intended?

Yes. There are three things that happened:
- First, I changed some definitions in the Kleisli category. I used `precomp_arr` and `postcomp_arr` more consistently, and that massively simplified the proofs. In those two files, there were lots of lines of code purely doing the equational reasoning to prove the laws, and those could compressed significantly.
- There are two ways to formulate enriched naturality. The one used for `nat_trans_enrichment` is the formulation as in Kelly's 'Basic Concepts of Enriched Categories'. However, now I use `nat_trans_enrichment_via_comp` systematically. That also significantly simplifies proofs. This also leads to a reduction in the number of lines of code
- Using this second change, I also finally found a proof that whenever a natural isomorphism is enriched, then its inverse is enriched as well. This way I could remove all proofs where I proof the enrichedness of inverses of natural isomorphisms.

**Comment by nmvdw** [comment]
For the third point: there used to be statements like `em_enriched_cat_ump_1_inv2cell_inv`, where I prove the enrichnedness of an inverse. The identifiers of such statements always have `_inv` in them somewhere, and those are removed. For the Kleisli category stuff: that involves around 3700 lines of code. That's why the diff is so huge.

**Review by benediktahrens — APPROVED** [review]

**Pull request merged**
