### PR TITLE
Subcategories of the precategory of precategories

### PR DESCRIPTION
**Pull request by siddharthist**
* Define the precategory of univalent categories
* Define the category of setcategories
* Show that these have terminal objects

### CODE REVIEW

**Comment by benediktahrens** [comment]
Interesting error message on Travis:
```
COQC UniMath/CategoryTheory/Subcategory/Limits.v
File "./UniMath/CategoryTheory/Subcategory/Limits.v", line 72, characters 0-9:
Error:
Anomaly
"File "vernac/classes.ml", line 379, characters 12-18: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

**Comment by DanGrayson** [comment]
Langston, that anomaly would be worth reporting, after trying to isolate the bug with Jason Gross' bug isolator.  There's an entry for doing that in the Makefile, if you'd like to give that a try, assuming you can get it to fail also on your machine.

**Comment by siddharthist** [comment]
@DanGrayson That's an awesome tool to have so integrated into the `Makefile`! Thanks for the tip.

I wasn't able to use it until I set `BUILD_COQ` to `yes`, perhaps it should override that option?

As a note to self, here's the command I ran:
```
nix-shell -p coq_8_8 ocaml ocamlPackages.findlib ocamlPackages.camlp5_strict --run "make isolate-bug BUGGY_FILE=CategoryTheory/Subcategory/Limits.v"
```
Here's the output:
```
(* -*- mode: coq; coq-prog-args: ("-emacs" "-indices-matter" "-type-in-type" "-noinit" "-w" "-notation-overridden,-local-declaration,+uniform-inheritance,-deprecated-option" "-R" "." "UniMath" "-top" "Limits") -*- *)
(* File reduced by coq-bug-finder from original input, then from 190 lines to 4 lines, then from 20 lines to 4 lines *)
(* coqc version 8.8.0 (May 2018) compiled on May 7 2018 12:51:22 with OCaml 4.05.0
   coqtop version 8.8.0 (May 2018) *)

Context .
```
And indeed, when replacing that whole file with just the one line, it still gives that error. I'll report upstream.

**Comment by siddharthist** [comment]
I've reported it: https://github.com/coq/coq/issues/7452

The error is due to an erroneous line in my PR, so I'll go ahead and fix that.

**Comment by DanGrayson** [comment]
Please resolve the conflict.
Here is a 3-way diff:
```
<<<<<<< HEAD
Definition is_setcategory (C : precategory) : UU := (isaset (ob C)) × (has_homsets C).
Definition setcategory : UU := total2 is_setcategory.
Definition category_from_setcategory (C : setcategory) : category :=
  (pr1 C,, (dirprod_pr2 (pr2 C))).
Coercion category_from_setcategory : setcategory >-> category.
||||||| merged common ancestors
Definition setcategory := total2 (
   λ C : precategory, dirprod (isaset (ob C)) (has_homsets C)).
=======
Definition object_hlevel (n : nat) (C : precategory) : hProp :=
  hProppair _ (isapropisofhlevel n (ob C)).

(* TODO: someday, [has_homsets] should be rephrased in terms of this *)
Definition homtype_hlevel (n : nat) (C : precategory) : hProp :=
  hProppair (∏ a b : C, isofhlevel n (C ⟦ a, b ⟧))
            (impred _ _ (λ _, impred _ _ (λ _, isapropisofhlevel n _))).

Definition object_homtype_hlevel (n m : nat) (C : precategory) : hProp :=
  object_hlevel n C ∧ homtype_hlevel m C.

Definition is_setcategory : precategory → hProp := object_homtype_hlevel 2 2.
Definition setcategory := total2 is_setcategory.
>>>>>>> 278a36e0953af5588b11291fc62507493a2ce8ab
```

**Comment by siddharthist** [comment]
Okay, I believe this is now current and working.

**Comment by benediktahrens** [comment]
There is another conflict, I am afraid.

**Comment by siddharthist** [comment]
Okay, conflict resolved (by a no-op, curiously).

**Comment by siddharthist** [comment]
Is there anything still holding this up?

**Comment by DanGrayson** [comment]
I just updated the branch again, so it's okay with me if we merge it after that.  Benedikt?

A good next result in this line is that the two categories are equivalent, using the axiom of choice.

**Pull request merged**
