### PR TITLE
Refactor Displayed Categories

### PR DESCRIPTION
**Pull request by m-lindgren**
Currently DisplayedCats is in need of a refactorisation. With this PR I suggest we split Core.v into the following

- Functors.v
- NaturalTransformations.v
- Isos.v
- Univalence.v
- Total.v
- Fiber.v

as well as merging Equivalences_bis.v with Equivalences.v. This also moves functor_lifting and section_disp to Constructions.v from Core.v to solve some dependencies (and I wasn't sure if they were important enough to be moved to separate files). In total this reduces Core.v from 2601 lines down to 404 lines.

Any changes made by me to existing code is recorded in small separate commits stating what I changed. I made no changes when moving large sections of code around beside indentation and possibly creating Sections.

This is of course not a complete refactoring of DisplayedCats, but it is a start.

### CODE REVIEW

**Comment by m-lindgren** [comment]
Some checks fail because files in TypeTheory and largecatmodules need to have some Require Imports added or changed. Here is a patch for [TypeTheory](https://github.com/m-lindgren/TypeTheory/commit/2e8bd36078168d18bb9679234661f6c48e69db01) and a patch for [largecatmodules](https://github.com/m-lindgren/largecatmodules/commit/6617c54446a890d77de0ebd8bd26b42864629c18) that works when I build them locally. I have not checked the changes in this PR against SetHITs, but I see no references to DisplayedCats in that library so I don't think that will cause any build issues.

**Comment by benediktahrens** [comment]
Dear @m-lindgren, thanks a lot for your PR. I'll take a look soon, hopefully today. Thanks also for providing fixes for the satellite repositories!

**Review by nmvdw — APPROVED** [review]
Thank you for this PR! I think this is a good and welcome change.

I have one suggestion: it might be good to move the section `Reindexing` (currently, in `Core.v`) to `Examples/Reindexing.v`.

**Comment by benediktahrens** [comment]
@m-lindgren : thanks again for preparing this PR. I am going to merge now. Would you mind filing PRs for TypeTheory and largecatmodules with the patches that you have already prepared as per https://github.com/UniMath/UniMath/pull/1448#issuecomment-1025452746 ?

**Comment by benediktahrens** [comment]
> Would you mind filing PRs for TypeTheory and largecatmodules with the patches that you have already prepared as per [#1448 (comment)](https://github.com/UniMath/UniMath/pull/1448#issuecomment-1025452746) ?

Nevermind, I have been able to do this myself.

**Pull request merged**
