### PR TITLE
[WIP] Fibration of bicategories

### PR DESCRIPTION
**Pull request by nmvdw**
This PR contains:
- Definition of (fully) faithful 1-cells in bicategories and examples of those
- Definition of binary products in bicategories
- Definition of a cleaving of bicategories
- Examples of cartesian cells (this part is WIP)
- Examples of cleavings of bicategories (this part is WIP)

### CODE REVIEW

**Comment by nmvdw** [comment]
@benediktahrens this PR is ready for review. Some points to pay attention to:
- Do you think the file Core/Faithful.v should be split in one file for faithful morphisms and one file for fully faithful morphisms?
- Any suggestions where to put `maponpaths_pr1_pathsdirprod`, `maponpaths_pr2_pathsdirprod`, and `pathsdirprod_eta`? Currently, they are in `Products.v`, but they should be in MoreFoundations. Same for `transportf_total2_paths_f` in `Codomain.v`
- Do you have suggestions for the name of the file `Domain.v`? A different name might be better (possibly something in the spirit of arrows into)
- What do you think of the approach taken in `Products.v` with regards to the usability? In the section `StandardFunctions`, I defined several functions which will commonly be used, and I also provided notation for them in`Notations`.

**Comment by benediktahrens** [comment]
The CI shows a file that is not being compiled:
```
--- checking every proof file is listed in one of the packages ---
error: *** file UniMath/Bicategories/PseudoFunctors/PseudoFunctorLimits.v not listed in appropriate file UniMath/*/.package/files
error: *** 1 unlisted proof files encountered
```

**Comment by benediktahrens** [comment]
> @benediktahrens this PR is ready for review. Some points to pay attention to:
> 
>     * Do you think the file Core/Faithful.v should be split in one file for faithful morphisms and one file for fully faithful morphisms?

No, I think it is fine. Possibly, renaming the file to `FullyFaithful.v` would be good.

>     * Any suggestions where to put `maponpaths_pr1_pathsdirprod`, `maponpaths_pr2_pathsdirprod`, and `pathsdirprod_eta`? Currently, they are in `Products.v`, but they should be in MoreFoundations. Same for `transportf_total2_paths_f` in `Codomain.v`

I think it would be fine to put them in `MoreFoundations/PartA`.

>     * Do you have suggestions for the name of the file `Domain.v`? A different name might be better (possibly something in the spirit of arrows into)

The current name seems good. 

>     * What do you think of the approach taken in `Products.v` with regards to the usability? In the section `StandardFunctions`, I defined several functions which will commonly be used, and I also provided notation for them in`Notations`.

That's great, I wish every file had an interface and notations like that. Maybe we should make the "Notations" stuff into a rule in the style guide?

**Comment by DanGrayson** [comment]
Regarding new notations, it would be good to add them to the list of reserved notations in `UniMath/Foundations/Init.v`, to prevent conflicts between files.

**Comment by nmvdw** [comment]
The comments are addressed in the latest commit.

**Comment by benediktahrens** [comment]
Build succeeded, CI failure due to changes to `Foundations` which in this instance are ok (reserved notations added). Merging.

**Pull request merged**
