### PR TITLE
remove destruct from most of Foundations

### PR DESCRIPTION
**Pull request by rmatthes**
replace the remaining uses of destruct by induction, except for those on natural numbers in NaturalNumbers.v
in PartB.v: remove the comment that the replacement was done until the position of the comment

This touches on Foundations, but is really very shallow.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Perhaps it's time to revive the discussion at https://github.com/UniMath/UniMath/issues/658, which was aimed a permitting `destruct` in certain cases.

**Comment by rmatthes** [comment]
Sadly, this question is still open one week before the UniMath school. Keeping very few `destruct` in Foundations is no good style, regardless of the outcome of the discussion. One should anyway admit that `induction` on Sigma-types produces `match` constructs, as if one had applied `destruct` (but this might change in the future). Why not `induction` whenever `destruct` and `induction` even have the same proof script? On natural numbers, I agree that `destruct` is more informative.

**Comment by DanGrayson** [comment]
I think there's no rush to resolve the question of relaxing the ban on `destruct`.  Meanwhile, this pull request is welcome and looks good to me.  For beginners, it is important to have not too many equivalent options.

**Comment by rmatthes** [comment]
@benediktahrens : please merge, the Travis failure is immaterial

**Comment by DanGrayson** [comment]
I wonder whether your comment "Keeping very few destruct in Foundations is no good style" should have been "Keeping very few destruct in Foundations is good style".

**Comment by benediktahrens** [comment]
lgtm

**Pull request merged**
