### PR TITLE
Substitution systems formalized

### PR DESCRIPTION
**Pull request by benediktahrens**
add a package "SubstitutionSystems" with a formalization of heterogeneous substitution systems

### CODE REVIEW

**Comment by benediktahrens** [comment]
Note that this PR is in conflict with #152 . It would probably be best to first pull in this one, and then amend #152 .

**Comment by benediktahrens** [comment]
Travis run failed after 50min 4sec because the time for one run is limited to 50min. Any ideas?
Maybe we should profit from the possibility to only build certain packages?

**Comment by DanGrayson** [comment]
But we want to test the whole thing.  Either we speed up your files or we stop using travis.  I'm running it now ...

**Comment by benediktahrens** [comment]
On 09/26/2015 01:00 PM, Daniel R. Grayson wrote:
> But we want to test the whole thing.  Either we speed up your files
> or we stop using travis.  I'm running it now ...

Having some packages tested is better than nothing.

I have already invested some time into speeding up those files, and for
now I don't have any ideas for how to make them compile faster.

**Comment by DanGrayson** [comment]
Well, no, we have to test everything.  The only question is whether we test
it at home or with travis.

**Comment by DanGrayson** [comment]
Here are the top 10 files, in terms of compile time:
```
UniMath/SubstitutionSystems/MonadsFromSubstitutionSystems (user: 565.42)
UniMath/SubstitutionSystems/LiftingInitial (user: 502.35)
UniMath/Foundations/hlevel2/algebra1b (user: 79.46)
UniMath/SubstitutionSystems/SumOfSignatures (user: 79.03)
UniMath/SubstitutionSystems/Lam (user: 69.29)
UniMath/Foundations/hlevel2/algebra1d (user: 50.32)
UniMath/SubstitutionSystems/LamSignature (user: 38.48)
UniMath/SubstitutionSystems/SubstitutionSystems (user: 35.58)
UniMath/Foundations/hlevel2/algebra1c (user: 30.81)
UniMath/SubstitutionSystems/Signatures (user: 23.34)
```

**Comment by DanGrayson** [comment]
Total time is 26 minutes on "dublin".

**Comment by DanGrayson** [comment]
Using 8 processors for parallel compilation cuts it to 16:
```
real	16m12.554s
user	38m27.269s
sys	0m42.750s
```

**Comment by DanGrayson** [comment]
On my Macbook Pro total time checking is 7 minutes with "-j4".  Here are the top times:
```
user time 308.14: UniMath/SubstitutionSystems/MonadsFromSubstitutionSystems
user time 287.90: UniMath/SubstitutionSystems/LiftingInitial
user time 50.93: UniMath/SubstitutionSystems/SumOfSignatures
user time 48.32: UniMath/Foundations/hlevel2/algebra1b
user time 38.26: UniMath/Foundations/hlevel2/algebra1d
user time 35.06: UniMath/SubstitutionSystems/Lam
user time 28.23: UniMath/SubstitutionSystems/LamSignature
user time 23.38: UniMath/Foundations/hlevel2/algebra1c
user time 21.20: UniMath/SubstitutionSystems/SubstitutionSystems
user time 12.10: UniMath/SubstitutionSystems/Signatures
user time 11.39: UniMath/Foundations/hlevel2/hq
```

**Pull request merged**
