### PR TITLE
Displayed category of sets

### PR DESCRIPTION
**Pull request by siddharthist**
Several things in `DisplayedCategories` needed to be generalized to precategories to make this go through. I think this example motivates those changes.

I hope to formulate more of the "hierarchy" of concrete categories as displayed categories over this one.

### CODE REVIEW

**Comment by benediktahrens** [comment]
```
COQC UniMath/CategoryTheory/DisplayedCats/Examples/HLevel.v
File "./UniMath/CategoryTheory/DisplayedCats/Examples/HLevel.v", line 22, characters 15-50:
Error: Unable to locate library UniMath.CategoryTheory.equivalences.
```

**Comment by siddharthist** [comment]
This has been updated to remove conflicts.

**Comment by siddharthist** [comment]
This has been updated to remove conflicts

**Comment by siddharthist** [comment]
I believe this should be fixed.

**Comment by siddharthist** [comment]
Ping @benediktahrens, I'm taking what's called "innovation time" at Galois this week to continue a few lines of work on UniMath and I'd like to build on this PR. Could it be merged?

**Pull request merged**
