### PR TITLE
Remove constr1

### PR DESCRIPTION
**Pull request by benediktahrens**
This change results, on my machine, in a reduction of compilation time of 5 minutes, from
```
real	61m32.310s
user	61m6.403s
sys	0m21.400s
```
down to
```
real	56m44.373s
user	56m23.948s
sys	0m20.228s
```
It would be great if someone could confirm this on a different machine.
After confirmation, I would advertise merging this.

### CODE REVIEW

**Comment by DanGrayson** [comment]
Some other changes appear to be needed.

**Comment by benediktahrens** [comment]
On 15/10/2019 20:33, Daniel R. Grayson wrote:
> Some other changes appear to be needed.

Oups, I had forgotten one commit. Now fixed

**Comment by DanGrayson** [comment]
Speaking of compile time, have you noticed that "Bicategories" takes 45 minutes?  Much more than  anything else.  Things are unbalanced.

**Comment by DanGrayson** [comment]
Travis doesn't confirm your impression that 5 minutes are saved:

Screen Shot 2019-10-16 at 7 09 21 AM

**Comment by benediktahrens** [comment]
On 16/10/2019 13:10, Daniel R. Grayson wrote:
> Travis doesn't confirm your impression that 5 minutes are saved:
> 
> Screen Shot 2019-10-16 at 7 09 21 AM 
> <https://user-images.githubusercontent.com/700228/66917987-02cbbf80-efe4-11e9-9a7f-0b0c4c546a33.png>

We have already seen that Travis measurements are not reproducible when 
we had problems with memory usage.

I think it would be good to test both versions on the same machine.

**Comment by DanGrayson** [comment]
On my machine cpu time and system time are almost identical:

Screen Shot 2019-10-16 at 1 22 48 PM

**Comment by benediktahrens** [comment]
On 16/10/2019 19:24, Daniel R. Grayson wrote:
> On my machine cpu time and system time are almost identical:

Thanks, then I will close this PR.

**Pull request closed without merging**
