### PR TITLE
Issue 40

### PR DESCRIPTION
**Pull request by DanGrayson**
fix it we don't have to run make twice

### CODE REVIEW

**Comment by benediktahrens** [comment]
On 05/06/2015 10:49 PM, Daniel R. Grayson wrote:
> fix it we don't have to run make twice

Awesome. I have tested it on my machine (Debian Wheezy, GNU make 3.81),
it works here.

**Comment by DanGrayson** [comment]
We should modify the travis script, too, so it runs "make" only once.

**Comment by benediktahrens** [comment]
On 05/07/2015 07:47 AM, Daniel R. Grayson wrote:
> We should modify the travis script, too, so it runs "make" only once.

Would you mind making this part of your PR? The file is 
UniMath/.travis.yml .


Would it be good to have a test file the compilation of which fails in 
case "make" does not compile the whole of UniMath?

At the moment, it just checks for exit status 0 of make, which would not 
discover problems we had with incomplete compilation.

For instance, one could explicitly compile a file test.v which imports a 
file from Ktheory.

Explicitly, I am thinking about amending the travis script with 
something like

make && make install
echo "Require Import UniMath.Ktheory.Elements." > test.v
./sub/coq/bin/coqc test.v

**Comment by DanGrayson** [comment]
oops, hold on, I checked in too much.

**Comment by DanGrayson** [comment]
transferring to https://github.com/UniMath/UniMath/pull/91

**Pull request closed without merging**
