### PR TITLE
Added example of a biadjunction

### PR DESCRIPTION
**Pull request by nmvdw**
I added an example of a biadjunction.
This is the biadjoint equivalence between 1-types and univalent groupoids.

### CODE REVIEW

**Comment by benediktahrens** [comment]
Nice!

I am a bit puzzled by what I see in Bicategories/PseudoFunctors/Biadjunction.v and in this PR: there are many occurrences of `biadj_data` in some form, but nothing without `data`.
In particular, the last thing defined in this PR that involves `biadj` in the name is
```
Definition path_groupoid_biadj_data
  : left_biadj_data path_groupoid.
```
https://github.com/UniMath/UniMath/pull/1256/files#diff-f5315681f6dadd56021d5c706a1f9f8cR571

Is there no `left_biadj`?

**Comment by nmvdw** [comment]
> Nice!
> 
> I am a bit puzzled by what I see in Bicategories/PseudoFunctors/Biadjunction.v and in this PR: there are many occurrences of `biadj_data` in some form, but nothing without `data`.
> In particular, the last thing defined in this PR that involves `biadj` in the name is
> 
> ```
> Definition path_groupoid_biadj_data
>   : left_biadj_data path_groupoid.
> ```
> 
> https://github.com/UniMath/UniMath/pull/1256/files#diff-f5315681f6dadd56021d5c706a1f9f8cR571
> 
> Is there no `left_biadj`?

Good point. In the code, there is no `left_biadj`, only `left_biadj_data` and `left_biadj_unit_counit`. I had the following naming scheme in mind:
- `left_biadj_unit_counit`: has right adjoint, unit and counit
- `left_biadj_data`: has right adjoint, unit, counit and modifications witnessing the triangle laws.
- `left_biadj`: has right adjoint, unit, counit and modifications witnessing the triangle laws, which satisfy the swallowtail equations. The swallowtail equations are formulated on page 10, 11 in:
https://arxiv.org/pdf/1102.0979.pdf

Comparing them with ncatlab (https://ncatlab.org/nlab/show/biadjunction#definition):
- `left_biadj_data` is an incoherent biadjunction.
- `left_biadj` is a coherent biadjunction.

Note: incoherent biadjunctions can be improved to coherent ones.

The notion of incoherent biadjunction is still useful. I think that being a left biadjoint is only a proposition when you require the swallowtail equations.

The name `left_incoherent_biadj`might have bee better than `left_biadj_data`, because the former does not imply that laws are necessary.

**Comment by benediktahrens** [comment]
On 17/07/2019 22:01, Niels van der Weide wrote:
>     Nice!
> 
>     I am a bit puzzled by what I see in
>     Bicategories/PseudoFunctors/Biadjunction.v and in this PR: there are
>     many occurrences of |biadj_data| in some form, but nothing without
>     |data|.
>     In particular, the last thing defined in this PR that involves
>     |biadj| in the name is
> 
>     |Definition path_groupoid_biadj_data : left_biadj_data path_groupoid. |
> 
>     https://github.com/UniMath/UniMath/pull/1256/files#diff-f5315681f6dadd56021d5c706a1f9f8cR571
> 
>     Is there no |left_biadj|?
> 
> Good point. In the code, there is no |left_biadj|, only 
> |left_biadj_data| and |left_biadj_unit_counit|. I had the following 
> naming scheme in mind:
> 
>   * |left_biadj_unit_counit|: has right adjoint, unit and counit
>   * |left_biadj_data|: has right adjoint, unit, counit and modifications
>     witnessing the triangle laws.
>   * |left_biadj|: has right adjoint, unit, counit and modifications
>     witnessing the triangle laws, which satisfy the swallowtail
>     equations. The swallowtail equations are formulated on page 10, 11 in:
>     https://arxiv.org/pdf/1102.0979.pdf
> 
> Comparing them with ncatlab 
> (https://ncatlab.org/nlab/show/biadjunction#definition):
> 
>   * |left_biadj_data| is an incoherent biadjunction.
>   * |left_biadj| is a coherent biadjunction.
> 
> Note: incoherent biadjunctions can be improved to coherent ones.
> 
> The notion of incoherent biadjunction is still useful. I think that 
> being a left biadjoint is only a proposition when you require the 
> swallowtail equations.
> 
> The name |left_incoherent_biadj|might have bee better than 
> |left_biadj_data|, because the former does not imply that laws are 
> necessary.

Thanks for the explanation!

The (implicit) convention is that the postfix "_data" is used for the 
data of some mathematical structure, yes. That's where my confusion 
comes from. |left_incoherent_biadj| or similar sounds good to me.

**Comment by benediktahrens** [comment]
Merging this now, maybe a renaming should follow later.

**Pull request merged**
