### PR TITLE
Axiom reorganization

### PR DESCRIPTION
**Pull request by DanGrayson**
This addresses #381.

It also removes the obsolete lemmas on eta-correction for functions.

Another option would be to preserve uahp as an axiom.

### CODE REVIEW

**Comment by benediktahrens** [comment]
Looks great, thanks!

**Comment by vladimirias** [comment]
Sorry Dan, but I don’t like it. We use funext and funextfun a lot and writing funextAxiom instead is a lot of extra typing.

I suggest we have funextTheorem and funext and similarly for others.

**Comment by DanGrayson** [comment]
Hmm, I don't understand your remark, since `funextfun` and `funextsec` are still there, and there is no need to type `funextAxiom`.  There never was a `funext`.

**Comment by DanGrayson** [comment]
Oops, wait a minute, I forgot to even use `funextAxiom` anywhere at all.  It should have been used in the proof of `funextsec`, but instead, it the proof of `funextsec` used univalence.  I'll fix that.

**Comment by vladimirias** [comment]
I think this is what caught my eye:

> Theorem isapropneg (X:UU): isaprop (neg X).
> -Proof. intro.  apply invproofirrelevance . intros x x' .   apply ( funextempty X x x' ) . Defined .
> +Proof. intro.  apply invproofirrelevance . intros x x' .   apply ( funextemptyAxiom X x x' ) . Defined .

**Comment by DanGrayson** [comment]
Yes, I like having axiom names ending with "Axiom".  That particular axiom is used only once, in `isapropneg`.

**Comment by DanGrayson** [comment]
Okay, I fixed that problem and isolated one more axiom from Vladimir's code.  I think it's all
okay now.

**Comment by vladimirias** [comment]
LGTM

**Pull request merged**
