### PR TITLE
remove ambiguous coercions from Foundations,

### PR DESCRIPTION
**Pull request by DanGrayson**
... MoreFoundations, and Combinatorics

Begins to address #1044 

In the process I moved my stuff on negative propositions into its own file in
`MoreFoundations`, leaving `Foundations` tidier.

### CODE REVIEW

**Comment by siddharthist** [comment]
@DanGrayson Did you forget to include the file `NegativePropositions`? 

Other than that omission, this LGTM!

**Comment by DanGrayson** [comment]
Oops, I've added it.

**Comment by DanGrayson** [comment]
I'm reluctant to add tables of contents to any files, because nothing checks that they are correct.

**Comment by siddharthist** [comment]
As someone who has fixed a few, I understand that worry. Sections (with `(** **`-style comments), however, are next to the code they divide (so are easy to maintain) and still provide good organization. If used with `outline-mode`, they can even provide folding. So including those might be nice, even in lieu of a TOC.

**Comment by DanGrayson** [comment]
Yes, I have two of those.

**Pull request merged**
