### PR TITLE
a small simplification that might make a Coq regression go away

### PR DESCRIPTION
**Pull request by rmatthes**

### CODE REVIEW

**Comment by m-lindgren** [comment]
lgtm, let's merge this when the current CI run for master is done.

**Review by m-lindgren — APPROVED** [review]

**Comment by benediktahrens** [comment]
In general I don't think UniMath should change to work around regressions in Coq. In this particular case, though, the changes are certainly desirable.

**Comment by rmatthes** [comment]
Clearly, my small changes simplify the file. But the former rewrites were a test bed for the identified equations, and their applicability is now even more questionable.

**Comment by m-lindgren** [comment]
This fixes part of it, but there are other problems: https://github.com/UniMath/UniMath/actions/runs/4331627549/jobs/7563581989#step:5:2134

**Comment by m-lindgren** [comment]
It worked! Thanks @rmatthes

**Pull request merged**
