### PR TITLE
Reorganize

### PR DESCRIPTION
**Pull request by DanGrayson**
We rename some files and directories, for human readability.

### CODE REVIEW

**Comment by benediktahrens** [comment]
lgtm

**Comment by DanGrayson** [comment]
PS: I've also removed the old coq patch files.

**Comment by DanGrayson** [comment]
PS: I also added Vladimir's simplicial sets file to the list of files that get built, and commented
out the proof that no longer works.

**Comment by DanGrayson** [comment]
I've brought this pull request up to date.  I expect travis will go too long, and we can stop using it until we speed up those new proofs.

**Comment by DanGrayson** [comment]
Benedikt, can you check it on your machine?  Let me know if you'd like to know a cool way to check a pull request with git.

**Comment by benediktahrens** [comment]
On 09/26/2015 04:05 PM, Daniel R. Grayson wrote:
> Benedikt, can you check it on your machine?  Let me know if you'd
> like to know a cool way to check a pull request with git.

Yes, I would love to know!

**Comment by DanGrayson** [comment]
Here's the way my upstream entry in .git/config looks:
```
[remote "upstream"]
url = git@github.com:UniMath/UniMath.git
fetch = +refs/heads/*:refs/remotes/upstream/*
fetch = +refs/pull/*/head:refs/remotes/upstream/pull/*
```

The final line arranges for pull requests to be fetched when you do
```git fetch --all```.  Then you get more remote branches, which are usable:
```
$ git branch -a | grep /pull/ | head
  remotes/upstream/pull/1
  remotes/upstream/pull/10
  remotes/upstream/pull/100
  remotes/upstream/pull/101
  remotes/upstream/pull/102
  remotes/upstream/pull/104
  remotes/upstream/pull/105
  remotes/upstream/pull/106
  remotes/upstream/pull/107
  remotes/upstream/pull/108
```

You can do something like ```git checkout pull/108``` and you'll have the
pull
request checked out, ready to test.  You can even merge it directly into the
upstream master branch, if you want to, and github will not get annoyed;
indeed,
it will observe the action and close the pull request.

**Comment by benediktahrens** [comment]
Travis finished successfully in time (42 minutes) - the run time varies by a lot. 
Thanks for showing us how to fetch pull requests, that makes life much easier.

**Comment by benediktahrens** [comment]
On 09/26/2015 04:30 PM, Daniel R. Grayson wrote:
> Here's the way my upstream entry in .git/config looks:
> ```
> [remote "upstream"]
> url = git@github.com:UniMath/UniMath.git
> fetch = +refs/heads/*:refs/remotes/upstream/*
> fetch = +refs/pull/*/head:refs/remotes/upstream/pull/*
> ```
>
> The final line arranges for pull requests to be fetched when you do
> ```git fetch --all```.  Then you get more remote branches, which are usable:
> ```
> $ git branch -a | grep /pull/ | head
>    remotes/upstream/pull/1
>    remotes/upstream/pull/10
>    remotes/upstream/pull/100
>    remotes/upstream/pull/101
>    remotes/upstream/pull/102
>    remotes/upstream/pull/104
>    remotes/upstream/pull/105
>    remotes/upstream/pull/106
>    remotes/upstream/pull/107
>    remotes/upstream/pull/108
> ```
>
> You can do something like ```git checkout pull/108``` and you'll have the
> pull
> request checked out, ready to test.  You can even merge it directly into the
> upstream master branch, if you want to, and github will not get annoyed;
> indeed,
> it will observe the action and close the pull request.


I have added a page [1] to the wiki, where I have put this info.

[1] https://github.com/UniMath/UniMath/wiki/Git-configuration-and-usage

**Pull request merged**
