### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by mortberg**
This fixes the issue I had with cloning and then making (without this change the modified version of Coq was never fetched).

### CODE REVIEW

**Comment by DanGrayson** [comment]
It's best not to depend much on ordering of prerequisites, because people might run ```make``` in parallel.   What about instead adding ```sub/coq/configure.ml``` as another target of the command ```git submodule update --init sub/coq```?  That ought to work for you.

**Comment by mortberg** [comment]
I hope I didn't misunderstand what you meant, but this works fine for me as well.

**Comment by DanGrayson** [comment]
Travis will probably like that, in which case it looks good.  Thanks!

**Comment by benediktahrens** [comment]
Anders, you have added some category theory stuff to that PR. Was that on purpose?

**Comment by mortberg** [comment]
No that was not intentional. I didn't know that if I push to my fork it will automatically be added to the pull request...

**Comment by mortberg** [comment]
Ok, now it should be fine and I have read up on how to properly develop using pull requests. Sorry for the confusion! :)

**Comment by DanGrayson** [comment]
Thanks!

**Pull request merged**
