### PR TITLE
Representable functors

### PR DESCRIPTION
**Pull request by DanGrayson**
Here is my latest material on representable functors in the Ktheory package.  One thing it includes
is a theorem that a family of representable functors gives a representable functor.

### CODE REVIEW

**Comment by benediktahrens** [comment]
lgtm

**Comment by benediktahrens** [comment]
@DanGrayson , could you fix the conflicts, please, so that I can merge?

**Comment by benediktahrens** [comment]
This PR changed the Coq submodule :-(

**Comment by DanGrayson** [comment]
Oops, I'll take a look.

**Comment by benediktahrens** [comment]
On 01/19/2016 10:41 AM, Daniel R. Grayson wrote:
> Oops, I'll take a look.

PR #273 should fix it.

**Pull request merged**
