### PR TITLE
guess how to fix a comment of VV

### PR DESCRIPTION
**Pull request by DanGrayson**
addresses #148 

Vladimir should check

### CODE REVIEW

**Comment by vladimirias** [comment]
I introduced that other definition to show what it was precisely that I meant by saying "naive definition".  I would suggest not to remove it but maybe make an extra comment saying that it is there for clarification only and is not used anywhere later.

**Comment by DanGrayson** [comment]
I didn't see anything sensible to replace ```weqgf00``` with, which is why I removed it.  Old versions of the code where the other two routines had their old names had nothing with that name.  What would you suggest replacing it with?

**Comment by vladimirias** [comment]
The same name that you gave to weqgf extended with _naive .

**Comment by DanGrayson** [comment]
The name ```homotinvweqweq_naive``` isn't currently being used, so it doesn't make sense to refer to it.  What's needed is the name of an existing lemma that formalizes the naive proof.

**Comment by vladimirias** [comment]
I meant the old lemma (what was it weqfg00?) renamed into homotinvweqweq_naive . Or there was no such lemma? Then I misunderstood.

**Comment by DanGrayson** [comment]
As far as I can tell, the old lemma weqfg00, presumed to exist by the
comment,
never did.  Hence the dilemma.

On Sat, Sep 5, 2015 at 2:35 PM, Vladimir Voevodsky <notifications@github.com

**Comment by vladimirias** [comment]
In the version that I have the names weqgf and weqfg are replaced in the main body of the code but not in comments.

**Comment by vladimirias** [comment]
I see now. Yes, your PR is what is needed - just please update it to have the right names in the comments.

**Comment by DanGrayson** [comment]
Re: "just please update it to have the right names in the comments."

So the pull request is not good enough yet?  If so, could you be more precise?  (I think
the pull request does provide the right names in the comments.)

**Pull request merged**
