### PR TITLE
Refactor category_hset_* into separate modules

### PR DESCRIPTION
**Pull request by siddharthist**
This has several advantages:

 1. It is easier to find the results you want when things are split up into logically coherent modules
 2. Faster compilation times
 3. It is more clear what other files are using from these modules

I plan to add a characterization of monics and strengthen that of epis to a weak equivalence after this is merged, so the `MonosEpisIsos` module will be more fleshed out.

### CODE REVIEW

**Comment by siddharthist** [comment]
I'm not sure what's going on with the Travis build:
```
make[1]: *** No rule to make target 'UniMath/CategoryTheory/categories/HSET/All.v', needed by '.coqdeps.d'.  Stop.
make[1]: Leaving directory '/UniMath'
make: *** [.coqdeps.d] Error 2
Makefile:366: recipe for target '.coqdeps.d' failed
```
https://travis-ci.org/UniMath/UniMath/jobs/456786500#L1594

**Comment by DanGrayson** [comment]
You didn't provide the file `UniMath/CategoryTheory/categories/HSET/All.v` that you listed in `.package/files`.

**Comment by DanGrayson** [comment]
Oops, that's my fault, fixed in #1063.

**Comment by siddharthist** [comment]
Thanks for the reviews, all!

**Pull request merged**
