### PR TITLE
replace Π with ∏ and Σ with ∑

### LINKED ISSUE #560: Π versus ∏ and ∑ versus Σ
I've just noticed that the Greek letter Π (\Pi) and the symbol for product ∏
(\prod) in Unicode are different.  We should switch, since we're using the
wrong one.  Similarly for sum.

### PR DESCRIPTION
**Pull request by DanGrayson**
because we should use the unicode math symbols, not the unicode Greek letters.

This resolves #560.

### CODE REVIEW

**Comment by DanGrayson** [comment]
This should be the next one to be pulled, since it will conflict with almost any new code that anyone writes in the meantime.  Too bad I didn't notice these symbols at the time of our original introduction of unicode.  

Comments?

**Comment by benediktahrens** [comment]
Will it make other PRs conflict?

Am 29. Januar 2017 17:50:06 MEZ schrieb "Daniel R. Grayson" <notifications@github.com>:
>This should be the next one to be pulled, since it will conflict with
>almost any new code that anyone writes in the meantime.  Too bad I
>didn't notice these symbols at the time of our original introduction of
>unicode.  
>
>Comments?

**Comment by DanGrayson** [comment]
Actually, it will be the test that fails: any PR that introduces one of the Greek letters will have to have it changed to the symbols.

But there will always be other PRs, no matter when we do this.

**Comment by DanGrayson** [comment]
Fixing a conflict is harder than fixing a failing test.  If another PR fails the test because it introduced the Greek letters, a single emacs command fixes it.  If this PR gets a conflict with the master branch, then I have to go through and remove all the conflict markers and repair them manually, and there might be dozens of them.

Of course, another PR could also get a conflict by modifying a line near a line with one of the Greek letters.

**Comment by DanGrayson** [comment]
On the other hand, I could always prepare a fresh version of the pull request by starting from the master branch, without having to resolve conflicts.  But when would be a good time to do that?

**Comment by DanGrayson** [comment]
Comments, anyone?  This one seems completely straightforward.

**Comment by vladimirias** [comment]
No special comments, but I thought that it would be good to wait with this one until as many as possible of the other PRs are closed.  I guess it is now such a time, since the remaining PRs are all fairly complicated and can not be closed right away, so LGTM.

**Pull request merged**
